# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems
from flag_gems.ops.sparse_mask import _FAST_JOIN_THRESHOLD, _keys_are_injective

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# sparse_mask projects a dense (or sparse COO) tensor onto a sparse COO mask:
# the output is a COO tensor with the mask's sparsity pattern and the values
# of `self` gathered at the mask indices. Coverage is driven by
#   - self layout (dense 2-D -> gather2d branch, dense N-D -> gather_nd
#     branch, sparse COO -> sparse intersection branch),
#   - mask shape/coalescing (coalesced, uncoalesced, duplicate entries,
#     0-nnz empty),
#   - dtype class of self (float/int/bool).
if QUICK_MODE:
    DENSE_SHAPES_ND = [(2, 3, 4)]
else:
    DENSE_SHAPES_ND = [(2, 3, 4), (4, 5, 6, 7)]

# (shape, nnz) pairs: nnz levels hit the single-entry case, the within-one-block
# case (BLOCK2D=512) and the multi-program case (1000 > 512); each nnz fits
# the paired shape.
if QUICK_MODE:
    CASES_2D = [((3, 4), 4)]
else:
    CASES_2D = [
        ((3, 4), 1),
        ((3, 4), 12),
        ((16, 33), 8),
        ((16, 33), 64),
        ((128, 256), 1000),
        ((128, 256), 4096),
    ]

DTYPES = utils.FLOAT_DTYPES + utils.INT_DTYPES + utils.BOOL_TYPES


def _make_coo_mask(shape, nnz, dtype, seed=0, coalesced=False):
    """A COO mask of the given shape/nnz whose entries are unique (so that
    coalesce() would not change them) but stored unsorted by default.

    Returns the built mask; callers must read back ``mask.is_coalesced()``
    instead of assuming the requested flag (a single-entry or already-sorted
    tensor is normalized to coalesced by the constructor itself).
    """
    gen = torch.Generator().manual_seed(seed)
    numel = 1
    for s in shape:
        numel *= s
    assert nnz <= numel, f"nnz={nnz} exceeds {shape} elements"
    flat = torch.randperm(numel, generator=gen)[:nnz]
    indices = torch.empty((len(shape), nnz), dtype=torch.int64)
    for d in reversed(range(len(shape))):
        indices[d] = flat % shape[d]
        flat = flat // shape[d]
    values = torch.ones(nnz, dtype=dtype)
    sparse = torch.sparse_coo_tensor(indices, values, tuple(shape))
    if coalesced:
        sparse = sparse.coalesce()
    return sparse.to(flag_gems.device)


@pytest.mark.sparse_mask
@pytest.mark.parametrize("shape,nnz", CASES_2D)
def test_accuracy_sparse_mask_dense_2d(shape, nnz):
    # Dense 2-D self: exercises the _gather2d_kernel branch (explicit
    # (stride0, stride1) address computation), coalesced and uncoalesced.
    self_t = torch.randn(shape, device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    for coalesced in (False, True):
        mask = _make_coo_mask(shape, nnz, torch.float32, seed=nnz, coalesced=coalesced)
        ref_mask = utils.to_reference(mask)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        res_out = flag_gems.sparse_mask(self_t, mask)

        assert res_out.layout == torch.sparse_coo
        assert res_out.shape == ref_out.shape
        # The flag follows the BUILT mask (native normalizes a single entry
        # or an already-sorted uncoalesced construction to coalesced=True).
        assert mask.is_coalesced() == ref_mask.is_coalesced()
        assert res_out.is_coalesced() == ref_out.is_coalesced() == mask.is_coalesced()
        utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
@pytest.mark.parametrize("shape", DENSE_SHAPES_ND)
def test_accuracy_sparse_mask_dense_nd(shape):
    # Dense N-D self (rank 3/4): exercises the _gather_nd_kernel branch with
    # the device-side stride tensor.
    self_t = torch.randn(shape, device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    nnz = 4 if not QUICK_MODE else 3
    mask = _make_coo_mask(shape, nnz, torch.float32, seed=5, coalesced=True)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.shape == ref_out.shape
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
@pytest.mark.parametrize("dtype", DTYPES)
def test_accuracy_sparse_mask_dtype_sweep(dtype):
    # Output dtype follows self (measured on native: float16/bfloat16/float32/
    # int16/int32/bool all supported; mask values are never read).
    self_t = torch.randn((3, 4), device=flag_gems.device).to(dtype)
    if dtype in utils.INT_DTYPES:
        self_t = torch.randint(
            torch.iinfo(dtype).min,
            torch.iinfo(dtype).max,
            (3, 4),
            dtype=dtype,
            device="cpu",
        ).to(flag_gems.device)
    elif dtype is torch.bool:
        self_t = torch.randint(0, 2, (3, 4), dtype=torch.bool, device="cpu").to(
            flag_gems.device
        )
    ref_self = utils.to_reference(self_t)

    mask = _make_coo_mask((3, 4), 3, dtype, seed=7, coalesced=True)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.dtype == ref_out.dtype == dtype
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), dtype)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_non_contiguous_self():
    # Transposed dense self: the gather must honour the non-contiguous strides
    # (2-D branch) exactly like native.
    self_t = torch.randn((4, 8), device=flag_gems.device).t()
    assert not self_t.is_contiguous()
    ref_self = utils.to_reference(self_t)

    mask = _make_coo_mask((8, 4), 5, torch.float32, seed=11, coalesced=True)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.shape == ref_out.shape
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_sparse_self():
    # Sparse COO self x COO mask: native projection semantics. The pattern is
    # the mask's, the VALUES are the mask's own values where the positions
    # intersect and zero elsewhere (measured native behaviour, see report):
    # e.g. self nnz-0 + mask nnz-2 -> mask pattern with zero values.
    for name, self_t, mask, exp_vals in [
        (
            "self-subset",
            _make_coo_mask((3, 4), 2, torch.float32, seed=1, coalesced=True),
            _make_coo_mask((3, 4), 4, torch.float32, seed=2, coalesced=True),
            None,
        ),
        (
            "self-empty",
            torch.sparse_coo_tensor(
                torch.zeros(2, 0, dtype=torch.int64, device=flag_gems.device),
                torch.zeros(0, device=flag_gems.device),
                (3, 4),
            ),
            _make_coo_mask((3, 4), 2, torch.float32, seed=3, coalesced=True),
            [0.0, 0.0],
            # native: pattern from mask, values all zero
        ),
        (
            "self-uncoalesced",
            _make_coo_mask((3, 4), 3, torch.float32, seed=4, coalesced=False),
            _make_coo_mask((3, 4), 3, torch.float32, seed=5, coalesced=True),
            None,
        ),
    ]:
        ref_self = utils.to_reference(self_t)
        ref_mask = utils.to_reference(mask)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        res_out = flag_gems.sparse_mask(self_t, mask)

        assert res_out.shape == ref_out.shape, name
        assert res_out.is_coalesced() == ref_out.is_coalesced(), name
        utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)
        if exp_vals is not None:
            got = res_out._values().cpu().tolist()
            assert got == exp_vals, f"{name}: {got} != {exp_vals}"


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_empty_mask():
    # 0-NNZ mask: output keeps the shape, nnz 0, and (measured native) the
    # mask's explicit is_coalesced() flag is PRESERVED -- an explicitly built
    # uncoalesced 0-nnz mask yields an uncoalesced 0-nnz output. (A 0-nnz
    # tensor built without the flag defaults to coalesced=True, which is what
    # the first probe measured.)
    self_t = torch.randn((3, 4), device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    for coalesced in (False, True):
        mask = torch.sparse_coo_tensor(
            torch.zeros(2, 0, dtype=torch.int64, device=flag_gems.device),
            torch.zeros(0, device=flag_gems.device),
            (3, 4),
            is_coalesced=coalesced,
        )
        assert mask.is_coalesced() == coalesced
        ref_mask = utils.to_reference(mask)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        res_out = flag_gems.sparse_mask(self_t, mask)

        assert res_out._nnz() == 0
        assert res_out.shape == ref_out.shape == torch.Size([3, 4])
        assert res_out.is_coalesced() == ref_out.is_coalesced() == coalesced
        # Both sides have no backing page for a 0-nnz sparse tensor.
        assert res_out._values().data_ptr() == ref_out._values().data_ptr() == 0


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_duplicate_entries():
    # Uncoalesced mask with duplicated coordinates: the output keeps the
    # mask's (unsorted, with dups) index order and gathers per-entry values.
    self_t = torch.arange(12, dtype=torch.float32, device=flag_gems.device).reshape(
        3, 4
    )
    ref_self = utils.to_reference(self_t)
    idx = torch.tensor(
        [[0, 0, 1], [1, 1, 2]], dtype=torch.int64, device=flag_gems.device
    )
    mask = torch.sparse_coo_tensor(idx, torch.ones(3, device=flag_gems.device), (3, 4))
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out._nnz() == 3
    assert res_out.is_coalesced() == ref_out.is_coalesced() is False
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    # Native gathers per entry (duplicates repeat), verified against manual.
    assert res_out._values().cpu().tolist() == ref_out._values().cpu().tolist()
    assert res_out._values().cpu().tolist() == [1.0, 1.0, 6.0]


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_1d():
    # 1-D dense self x 1-D COO mask: rank-1 edge of the 2-D/ND branches.
    self_t = torch.arange(8, dtype=torch.float32, device=flag_gems.device)
    mask = torch.sparse_coo_tensor(
        torch.tensor([[0, 3, 7]], dtype=torch.int64, device=flag_gems.device),
        torch.ones(3, device=flag_gems.device),
        (8,),
    ).coalesce()
    ref_self = utils.to_reference(self_t)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.shape == ref_out.shape == torch.Size([8])
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)
    assert res_out._values().cpu().tolist() == [0.0, 3.0, 7.0]


@pytest.mark.sparse_mask
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32, torch.int32])
def test_accuracy_sparse_mask_dtype_follows_self(dtype):
    # Mask values dtype is irrelevant (never read): even a float32-valued mask
    # on an int16 self yields int16 output (measured native behaviour).
    if dtype is torch.int32:
        self_t = torch.randint(-100, 100, (3, 4), dtype=torch.int32).to(
            flag_gems.device
        )
        mask_dtype = torch.float32
    else:
        self_t = torch.randn((3, 4), device=flag_gems.device).to(dtype)
        mask_dtype = dtype
    mask = _make_coo_mask((3, 4), 3, mask_dtype, seed=9, coalesced=True)
    ref_self = utils.to_reference(self_t)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.dtype == ref_out.dtype == dtype


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_fresh_storage():
    # Native allocates a fresh COO tensor: the output's indices/values must
    # not share storage with the mask's (values are gathered fresh; the
    # indices come from a clone). A 0-nnz output has no backing page on either
    # side (both data_ptrs are 0), which is excluded below.
    self_t = torch.randn((3, 4), device=flag_gems.device)
    mask = _make_coo_mask((3, 4), 4, torch.float32, seed=13)
    res_out = flag_gems.sparse_mask(self_t, mask)

    # Sparsity structure parity: the output must report the mask's sparse_dim
    # and dense_dim, not just the same shape.
    assert res_out.sparse_dim() == mask.sparse_dim()
    assert res_out.dense_dim() == mask.dense_dim()
    assert res_out._values().shape == (res_out._nnz(),)
    assert res_out._values().untyped_storage().data_ptr() != (
        mask._values().untyped_storage().data_ptr()
    )
    assert res_out._indices().untyped_storage().data_ptr() != (
        mask._indices().untyped_storage().data_ptr()
    )
    assert res_out._base is None
    assert res_out is not mask
    # Input untouched.
    assert mask._nnz() == 4
    # Self is never written.
    snapshot = self_t.clone()
    assert torch.equal(self_t, snapshot)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_error_paths():
    # Native-parity rejections (measured): a size mismatch must raise
    # RuntimeError like native; a dense or CSR mask raises NotImplementedError
    # because only the sparse COO mask path is implemented (native supports
    # CSR masks through a separate compressed-layout kernel).
    self_t = torch.randn((3, 4), device=flag_gems.device)

    m56 = _make_coo_mask((5, 6), 3, torch.float32, seed=17)
    with pytest.raises(RuntimeError, match="incompatible sizes"):
        flag_gems.sparse_mask(self_t, m56)

    dense_mask = torch.randn((3, 4), device=flag_gems.device)
    with pytest.raises(NotImplementedError, match="COO"):
        flag_gems.sparse_mask(self_t, dense_mask)

    csr_mask = _make_coo_mask((3, 4), 3, torch.float32, seed=19, coalesced=True)
    csr_mask = csr_mask.to_sparse_csr()
    with pytest.raises(NotImplementedError, match="COO"):
        flag_gems.sparse_mask(self_t, csr_mask)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_hybrid_mask_rejected():
    # Hybrid COO mask (dense_dim > 0): native serves it through its own
    # hybrid path (values shaped (nnz, *dense_shape)); this COO-only
    # implementation allocates a flat (nnz,) values buffer, so it must reject
    # the mask instead of failing with the constructor's unrelated
    # "number of dimensions must be sparse_dim (1) + dense_dim (0), but got 2"
    # RuntimeError.
    self_t = torch.randn((4, 3), device=flag_gems.device)
    mask = torch.sparse_coo_tensor(
        torch.tensor([[0, 2]], dtype=torch.int64, device=flag_gems.device),
        torch.randn((2, 3), device=flag_gems.device),
        (4, 3),
    )
    assert mask.layout == torch.sparse_coo
    assert mask.sparse_dim() == 1
    assert mask.dense_dim() == 1
    # Native accepts this input and returns a hybrid result, so the guard is a
    # deliberate capability gap, not a malformed-input rejection. The reference
    # call uses to_reference on BOTH operands so it also holds under --ref=cpu.
    ref_out = torch.ops.aten.sparse_mask(
        utils.to_reference(self_t), utils.to_reference(mask)
    )
    assert ref_out.dense_dim() == 1

    with pytest.raises(NotImplementedError, match="dense_dim > 0"):
        flag_gems.sparse_mask(self_t, mask)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_dispatch_sentinel():
    # Registration-path check (fresh-process sentinel matrix in the report):
    # a dense self x COO mask resolves on the MASK's SparseCUDA key -- the
    # plain CUDA key never sees this call. A sentinel on SparseCUDA must
    # intercept every real call form.
    hits = []

    def sentinel(self, mask):
        hits.append(str(mask.layout))
        return flag_gems.sparse_mask(self, mask)

    lib = torch.library.Library("aten", "IMPL")
    lib.impl("sparse_mask", sentinel, "SparseCUDA")

    dev = flag_gems.device
    d = torch.randn((3, 4), device=dev)
    mask = _make_coo_mask((3, 4), 3, torch.float32, seed=19)
    assert torch.ops.aten.sparse_mask(d, mask)._nnz() == 3
    assert d.sparse_mask(mask)._nnz() == 3
    assert torch.Tensor.sparse_mask(d, mask)._nnz() == 3
    assert len(hits) == 3
    assert set(hits) == {"torch.sparse_coo"}
    # The plain-CUDA key is NOT on the path (dense x dense natively raises
    # NotImplementedError from the CUDA backend before reaching us).


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_coexistence():
    # A sentinel on SparseCsrCUDA must NOT intercept COO-mask calls: the CSR
    # path stays native. Both keys must coexist without cross-routing.
    coo_hits = []

    def sentinel_coo(self, mask):
        coo_hits.append(str(mask.layout))
        return flag_gems.sparse_mask(self, mask)

    lib = torch.library.Library("aten", "IMPL")
    lib.impl("sparse_mask", sentinel_coo, "SparseCUDA")

    dev = flag_gems.device
    d = torch.randn((3, 4), device=dev)
    mask = _make_coo_mask((3, 4), 3, torch.float32, seed=23, coalesced=True)
    assert torch.ops.aten.sparse_mask(d, mask)._nnz() == 3
    assert coo_hits == ["torch.sparse_coo"]
    # CSR mask takes the native SparseCsrCUDA kernel (untouched here).
    ref = torch.ops.aten.sparse_mask(d, mask.to_sparse_csr())
    assert ref.layout == torch.sparse_csr
    assert len(coo_hits) == 1  # not re-routed


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_dispatch_stability():
    # Repeated dispatches plus an unrelated aten op in between must not
    # corrupt results (no cross-call state in the implementation).
    self_t = torch.randn((3, 4), device=flag_gems.device)
    mask = _make_coo_mask((3, 4), 4, torch.float32, seed=29, coalesced=True)
    ref_out = torch.ops.aten.sparse_mask(
        utils.to_reference(self_t), utils.to_reference(mask)
    )
    for _ in range(3):
        res_out = flag_gems.sparse_mask(self_t, mask)
        utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)
        assert torch.ops.aten.dim(self_t) == 2
    assert res_out._nnz() == 4


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_large_2d():
    # Multi-program path: nnz beyond one 512-block; uncoalesced order.
    shape = (33, 65)
    self_t = torch.randn(shape, device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    nnz = 1000 if not QUICK_MODE else 4
    mask = _make_coo_mask(shape, nnz, torch.float32, seed=31)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out._nnz() == nnz
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
@pytest.mark.parametrize("nnz_self,nnz_mask", [(1000, 400), (400, 1000), (2000, 2000)])
def test_accuracy_sparse_mask_sparse_self_large(nnz_self, nnz_mask):
    # Large sparse x sparse intersection: exercises the fast join path beyond
    # toy sizes (both operands above one _BLOCKSP program; mask larger than
    # self and vice versa). Uncoalesced self exercises the last-match-wins
    # bookkeeping against the native reference (no duplicate coordinates are
    # generated by _make_coo_mask, so native stays a valid reference here).
    self_t = _make_coo_mask(
        (128, 256), nnz_self, torch.float32, seed=nnz_self, coalesced=False
    )
    mask = _make_coo_mask(
        (128, 256), nnz_mask, torch.float32, seed=nnz_mask + 1, coalesced=True
    )
    ref_self = utils.to_reference(self_t)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out.shape == ref_out.shape
    assert res_out.is_coalesced() == ref_out.is_coalesced() == mask.is_coalesced()
    utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_duplicate_self_last_match():
    # Duplicate coordinates in the sparse SELF: the winner is the LAST match
    # in the self's storage order (documented last-match-wins rule; native's
    # intersection kernel instead sums duplicates, so the expected values are
    # stated explicitly rather than taken from the native reference).
    self_t = torch.sparse_coo_tensor(
        torch.tensor(
            [[1, 0, 1, 2], [1, 0, 1, 3]], dtype=torch.int64, device=flag_gems.device
        ),
        torch.tensor([5.0, 7.0, 9.0, 11.0], device=flag_gems.device),
        (3, 4),
    )
    mask = torch.sparse_coo_tensor(
        torch.tensor([[1, 0], [1, 0]], dtype=torch.int64, device=flag_gems.device),
        torch.ones(2, device=flag_gems.device),
        (3, 4),
    )
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out._indices().cpu().tolist() == [[1, 0], [1, 0]]
    assert res_out._values().cpu().tolist() == [9.0, 7.0]


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_duplicate_self_unsorted_mask():
    # Same duplicate-self rule with an UNCOALESCED mask that requests the
    # duplicated coordinate twice in different storage positions: each mask
    # entry independently gathers the last matching self entry.
    self_t = torch.sparse_coo_tensor(
        torch.tensor(
            [[2, 0, 1], [3, 0, 1]], dtype=torch.int64, device=flag_gems.device
        ),
        torch.tensor([1.0, 2.0, 3.0], device=flag_gems.device),
        (3, 4),
    )
    # mask: (1,1) at positions 0 and 2, (0,0) at position 1
    mask = torch.sparse_coo_tensor(
        torch.tensor(
            [[1, 0, 1], [1, 0, 1]], dtype=torch.int64, device=flag_gems.device
        ),
        torch.ones(3, device=flag_gems.device),
        (3, 4),
    )
    res_out = flag_gems.sparse_mask(self_t, mask)

    # self storage: (2,3)=1.0, (0,0)=2.0, (1,1)=3.0 -> last match per mask entry
    assert res_out._values().cpu().tolist() == [3.0, 2.0, 3.0]


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_sparse_self_threshold_boundary():
    # nnz_s near the fast-path threshold boundary: both sides of the boundary
    # must produce identical results (the threshold is an implementation
    # detail, not semantics).
    shape = (64, 64)
    for nnz_s in (_FAST_JOIN_THRESHOLD - 1, _FAST_JOIN_THRESHOLD):
        self_t = _make_coo_mask(shape, nnz_s, torch.float32, seed=41, coalesced=False)
        mask = _make_coo_mask(shape, 3000, torch.float32, seed=43, coalesced=True)
        ref_self = utils.to_reference(self_t)
        ref_mask = utils.to_reference(mask)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        res_out = flag_gems.sparse_mask(self_t, mask)

        utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
@pytest.mark.sparse_mask_out
def test_accuracy_sparse_mask_out():
    # .out overload: writes the projection into a preallocated COO buffer and
    # returns that buffer itself (measured native contract).
    self_t = torch.randn((4, 8), device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    mask = _make_coo_mask((4, 8), 5, torch.float32, seed=13, coalesced=True)
    ref_mask = utils.to_reference(mask)

    ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
    # The buffer's pattern/flags deliberately do NOT match the result, so
    # "was it overwritten?" is unambiguous.
    out_buf = torch.sparse_coo_tensor(
        torch.zeros(2, 1, dtype=torch.int64, device=flag_gems.device),
        torch.full((1,), -7.0, device=flag_gems.device),
        (4, 8),
        is_coalesced=True,
    )
    ret = flag_gems.sparse_mask_out(self_t, mask, out=out_buf)

    assert ret is out_buf
    assert out_buf.shape == ref_out.shape
    assert out_buf._nnz() == ref_out._nnz()
    assert out_buf.is_coalesced() == ref_out.is_coalesced() == mask.is_coalesced()
    utils.gems_assert_close(out_buf._indices(), ref_out._indices(), torch.int64)
    utils.gems_assert_close(out_buf._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_out_matches_functional():
    # .out and the functional form agree on every covered input class (dense
    # 2-D self, dense 3-D self, sparse self).
    for name, self_t in [
        ("dense2d", torch.randn((3, 4), device=flag_gems.device)),
        ("dense3d", torch.randn((2, 3, 4), device=flag_gems.device)),
        (
            "sparse",
            _make_coo_mask((3, 4), 3, torch.float32, seed=3, coalesced=True),
        ),
    ]:
        ref_self = utils.to_reference(self_t)
        mask = _make_coo_mask(tuple(self_t.shape), 4, torch.float32, seed=17)
        ref_mask = utils.to_reference(mask)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        fun_out = flag_gems.sparse_mask(self_t, mask)
        out_buf = torch.sparse_coo_tensor(
            torch.zeros(
                mask.sparse_dim(), 0, dtype=torch.int64, device=flag_gems.device
            ),
            torch.zeros(0, device=flag_gems.device),
            tuple(self_t.shape),
        )
        out_out = flag_gems.sparse_mask_out(self_t, mask, out=out_buf)

        assert out_out._nnz() == ref_out._nnz(), name
        utils.gems_assert_close(out_out._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(
            out_out._values(), ref_out._values(), ref_out._values().dtype
        )
        # Both sides of the functional/.out comparison go through to_reference so
        # they live on the same device under --ref=cpu too.
        utils.gems_assert_close(
            utils.to_reference(fun_out._values()),
            utils.to_reference(out_out._values()),
            ref_out._values().dtype,
        )


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_out_fresh_pattern():
    # The .out result adopts the MASK's pattern, not the buffer's: a buffer
    # preallocated with a different pattern/nnz is fully overwritten (native
    # parity measured on this build), and writing into it never reaches the
    # mask or the self.
    self_t = torch.randn((4, 5), device=flag_gems.device)
    mask = _make_coo_mask((4, 5), 4, torch.float32, seed=23)
    out_buf = torch.sparse_coo_tensor(
        torch.tensor([[0, 1], [0, 1]], dtype=torch.int64, device=flag_gems.device),
        torch.full((2,), -7.0, device=flag_gems.device),
        (4, 5),
        is_coalesced=True,
    )
    ret = flag_gems.sparse_mask_out(self_t, mask, out=out_buf)

    assert ret is out_buf
    assert out_buf._nnz() == 4
    assert torch.equal(out_buf._indices().cpu(), mask._indices().cpu())
    # The buffer is a copy target: writing it does not reach the inputs.
    mask_before = mask._indices().clone()
    self_before = self_t.clone()
    out_buf._values().fill_(99.0)
    assert torch.equal(mask._indices(), mask_before)
    assert torch.equal(self_t, self_before)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_out_rejects_bad_buffer():
    # Dtype/device/shape mismatches raise like native's generated .out kernel.
    self_t = torch.randn((3, 4), device=flag_gems.device)
    mask = _make_coo_mask((3, 4), 3, torch.float32, seed=19, coalesced=True)

    with pytest.raises(RuntimeError, match="dtype"):
        flag_gems.sparse_mask_out(
            self_t,
            mask,
            out=torch.sparse_coo_tensor(
                mask._indices().clone(),
                torch.zeros(3, dtype=torch.float64, device=flag_gems.device),
                (3, 4),
            ),
        )
    with pytest.raises(RuntimeError, match="device"):
        flag_gems.sparse_mask_out(
            self_t,
            mask,
            out=torch.sparse_coo_tensor(
                mask._indices().clone().cpu(),
                torch.zeros(3, device="cpu"),
                (3, 4),
            ),
        )
    with pytest.raises(RuntimeError, match="shape"):
        flag_gems.sparse_mask_out(
            self_t,
            mask,
            out=torch.sparse_coo_tensor(
                torch.zeros(2, 0, dtype=torch.int64, device=flag_gems.device),
                torch.zeros(0, device=flag_gems.device),
                (5, 6),
            ),
        )


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_out_zero_entries():
    # 0-nnz mask: the buffer is rebuilt with the mask's empty pattern, keeps
    # the mask's coalesced flag, and is still returned (native parity).
    self_t = torch.randn((3, 4), device=flag_gems.device)
    for coalesced in (False, True):
        mask = torch.sparse_coo_tensor(
            torch.zeros(2, 0, dtype=torch.int64, device=flag_gems.device),
            torch.zeros(0, device=flag_gems.device),
            (3, 4),
            is_coalesced=coalesced,
        )
        ref_mask = utils.to_reference(mask)
        ref_self = utils.to_reference(self_t)

        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)
        out_buf = torch.sparse_coo_tensor(
            torch.tensor([[0, 1], [1, 2]], dtype=torch.int64, device=flag_gems.device),
            torch.full((2,), -7.0, device=flag_gems.device),
            (3, 4),
        )
        ret = flag_gems.sparse_mask_out(self_t, mask, out=out_buf)

        assert ret is out_buf
        assert out_buf._nnz() == 0
        assert out_buf.is_coalesced() == ref_out.is_coalesced() == coalesced


@pytest.mark.sparse_mask
@pytest.mark.sparse_mask_out
def test_accuracy_sparse_mask_out_reuses_one_buffer_across_calls():
    # ONE buffer, TWO calls with different masks/nnz: the second call must fully
    # replace the state left by the first (nnz, indices, values, coalesced flag)
    # rather than merging into it or returning a new tensor -- the whole point
    # of the .out contract when a caller recycles a buffer in a loop.
    self_t = torch.randn((4, 6), device=flag_gems.device)
    ref_self = utils.to_reference(self_t)
    out_buf = torch.sparse_coo_tensor(
        torch.zeros(2, 0, dtype=torch.int64, device=flag_gems.device),
        torch.zeros(0, device=flag_gems.device),
        (4, 6),
    )

    for mask_nnz, seed, coalesced in ((9, 31, True), (2, 37, False)):
        # nnz and coalesced flag differ between the two calls, so stale state
        # from call 1 cannot masquerade as the result of call 2.
        mask = _make_coo_mask((4, 6), mask_nnz, torch.float32, seed=seed)
        assert mask._nnz() == mask_nnz, "mask fixture lost entries"
        ref_mask = utils.to_reference(mask)
        ref_out = torch.ops.aten.sparse_mask(ref_self, ref_mask)

        ret = flag_gems.sparse_mask_out(self_t, mask, out=out_buf)

        assert ret is out_buf
        assert out_buf._nnz() == mask_nnz, "stale nnz from the previous call"
        assert out_buf.is_coalesced() == ref_out.is_coalesced()
        utils.gems_assert_close(out_buf._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(out_buf._values(), ref_out._values(), torch.float32)


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_sparse_self_fast_join_routing():
    # FALSIFIABLE routing contract of the sparse x sparse branch (this test
    # fails against the pre-fix implementation, which never sorts): at or above
    # the fast-join threshold the implementation sorts the self keys and
    # binary-searches them -- observable as a torch.sort call over an int64 1-D
    # key tensor during the call -- while below the threshold the legacy
    # per-dimension scan runs and issues no such sort. Results are identical by
    # construction, so both routes are also checked against the reference.
    shape = (64, 64)
    seen = []
    real_sort = torch.sort

    def spy_sort(inp, *args, **kwargs):
        if torch.is_tensor(inp) and inp.dtype == torch.int64 and inp.dim() == 1:
            seen.append(int(inp.numel()))
        return real_sort(inp, *args, **kwargs)

    torch.sort = spy_sort
    try:
        # Above the threshold: the sorted-join path runs.
        big_self = _make_coo_mask(shape, 4096, torch.float32, seed=51, coalesced=False)
        mask_big = _make_coo_mask(shape, 3000, torch.float32, seed=53, coalesced=True)
        ref_out = torch.ops.aten.sparse_mask(
            utils.to_reference(big_self), utils.to_reference(mask_big)
        )
        res_out = flag_gems.sparse_mask(big_self, mask_big)
        assert seen, "fast join path did not sort the self keys"
        utils.gems_assert_close(res_out._indices(), ref_out._indices(), torch.int64)
        utils.gems_assert_close(res_out._values(), ref_out._values(), torch.float32)

        # Below the threshold: the legacy scan runs and issues no such sort.
        seen.clear()
        small_self = _make_coo_mask(shape, 64, torch.float32, seed=55, coalesced=False)
        mask_small = _make_coo_mask(shape, 3000, torch.float32, seed=57, coalesced=True)
        ref_out2 = torch.ops.aten.sparse_mask(
            utils.to_reference(small_self), utils.to_reference(mask_small)
        )
        res_out2 = flag_gems.sparse_mask(small_self, mask_small)
        assert not seen, "legacy path should not sort"
        utils.gems_assert_close(res_out2._indices(), ref_out2._indices(), torch.int64)
        utils.gems_assert_close(res_out2._values(), ref_out2._values(), torch.float32)
    finally:
        torch.sort = real_sort


@pytest.mark.sparse_mask
def test_accuracy_sparse_mask_sparse_self_out_of_range_keys():
    # REGRESSION GUARD for the linear-key join (not falsifiable against the
    # pre-fix implementation, which has no key join): the key is only injective
    # for IN-RANGE coordinates -- (9, 0) and (1, 1) collide at key 5 in a (3, 4)
    # shape -- so an out-of-range self index must never be matched by an
    # in-range mask entry that merely shares its key. Native zeroes the result
    # for out-of-range self coordinates, so that is the expected value.
    shape = (3, 4)
    self_t = torch.sparse_coo_tensor(
        torch.tensor(
            [[0, 9, 0], [0, 0, 9]], dtype=torch.int64, device=flag_gems.device
        ),
        torch.tensor([2.0, 5.0, 7.0], device=flag_gems.device),
        shape,
    )
    # mask: (0,0) in range; (1,1) in range with the colliding key 5.
    mask = torch.sparse_coo_tensor(
        torch.tensor([[0, 1], [0, 1]], dtype=torch.int64, device=flag_gems.device),
        torch.ones(2, device=flag_gems.device),
        shape,
    )
    res_out = flag_gems.sparse_mask(self_t, mask)

    assert res_out._indices().cpu().tolist() == [[0, 1], [0, 1]]
    assert res_out._values().cpu().tolist() == [2.0, 0.0]


@pytest.mark.sparse_mask
def test_keys_are_injective_guard():
    # Unit test of the fast path's eligibility guard: the linear key may only
    # be used when it separates every coordinate. Out-of-range coordinates
    # collide by construction -- (9, 0) and (1, 1) both map to key 5 under
    # shape (3, 4) -- so the guard must reject them and route those inputs to
    # the per-dimension scan.
    def coo(rows, cols):
        return torch.tensor([rows, cols], dtype=torch.int64, device=flag_gems.device)

    assert _keys_are_injective(coo([0, 1, 2], [0, 3, 1]), (3, 4), 2, 3)
    assert not _keys_are_injective(coo([0, 9], [0, 0]), (3, 4), 2, 2)
    assert not _keys_are_injective(coo([0, 0], [0, 9]), (3, 4), 2, 2)
    assert not _keys_are_injective(coo([-1, 0], [0, 0]), (3, 4), 2, 2)
    # The colliding pair whose key equality the guard exists to catch.
    assert not _keys_are_injective(coo([9, 1], [0, 1]), (3, 4), 2, 2)
