# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``aten::coalesce`` is a sparse-COO structural op: it sorts the index columns
# lexicographically and adds together the values of duplicate columns. The
# assertions below therefore compare (is_coalesced, nnz, indices, values,
# shape, sparse_dim, dense_dim) against the reference, and pin the object
# identity contract for the already-coalesced / zero-nnz paths.
#
# Native metadata captured with CUDA_VISIBLE_DEVICES="" in the container
# (runs/coalesce/probe_native_cpu.log, probe_keygrid2.log):
#   - fresh object for an uncoalesced input, ``is_coalesced() == True``;
#   - the SAME object is returned when the input is already coalesced;
#   - zero-nnz COO tensors report ``is_coalesced() == True`` (so they take the
#     identity path too); a hybrid COO tensor is uncoalesced even with nnz=1;
#   - the input is never mutated;
#   - non-COO layouts raise RuntimeError (Strided / SparseCsr / SparseBsc);
#   - the native output's indices tensor is NOT contiguous; the submitted
#     implementation's is contiguous. That difference is not asserted.
setattr(
    pytest.mark,
    "coalesce",
    MarkDecorator(Mark("coalesce", (), {}, _ispytest=True), _ispytest=True),
)

# (sparse_dim, nnz, size) triples. Duplicate index columns are present in every
# case so the value-accumulation branch is always exercised. The nnz=2000 case
# crosses the small path's 1024-entry ceiling for every dtype routed through it
# (fp64/ints/bool): before the scan-path rerouting those dtypes silently
# dropped every entry past the 1024th (reviewer-reported data-loss bug), so
# this row is the regression guard for the routing fix.
COO_CASES = [(2, 6, (4, 5)), (2, 2000, (50, 50))]
if not QUICK_MODE:
    COO_CASES += [
        (1, 8, (16,)),
        (2, 64, (16, 16)),
        (3, 48, (5, 7, 9)),
        (2, 300, (32, 32)),
    ]

# The float path takes fp16/fp32/bf16; every other dtype goes through the
# small path. QUICK_MODE keeps one dtype from each path plus bool (which has
# its own finalize branch) so coverage cannot be silently dropped.
CASES_DTYPES = [torch.float32, torch.bool]
if not QUICK_MODE:
    CASES_DTYPES = [
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.float64,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.uint8,
        torch.bool,
    ]


def _make_coo(nnd, nnz, size, dtype, device, seed=0):
    """Build an *uncoalesced* sparse COO tensor with duplicate index columns.

    Indices are drawn with replacement from the flattened index space so
    duplicates exist by construction; the rows are then permuted so the input
    is not already sorted (an already-sorted duplicate-free input would take
    the identity path and never exercise the kernels).
    """
    gen = torch.Generator(device="cpu").manual_seed(seed)
    numel = 1
    for s in size[:nnd]:
        numel *= s
    flat = torch.randint(0, numel, (nnz,), generator=gen, dtype=torch.int64)
    indices = torch.empty((nnd, nnz), dtype=torch.int64)
    for d in reversed(range(nnd)):
        indices[d] = flat % size[d]
        flat = flat // size[d]
    perm = torch.randperm(nnz, generator=gen)
    indices = indices[:, perm].contiguous()
    if dtype.is_floating_point:
        values = torch.randn(nnz, generator=gen).to(dtype)
    elif dtype == torch.bool:
        values = torch.randint(0, 2, (nnz,), generator=gen).to(dtype)
    else:
        values = torch.randint(0, 6, (nnz,), generator=gen).to(dtype)
    return torch.sparse_coo_tensor(indices.to(device), values.to(device), size)


def _assert_same_structure(res, ref, dtype):
    assert res.is_coalesced() is True
    assert res.is_coalesced() == ref.is_coalesced()
    assert res.layout == ref.layout
    assert tuple(res.shape) == tuple(ref.shape)
    assert res.sparse_dim() == ref.sparse_dim()
    assert res.dense_dim() == ref.dense_dim()
    assert res._nnz() == ref._nnz()
    utils.gems_assert_equal(res._indices(), ref._indices())
    utils.gems_assert_close(res._values(), ref._values(), dtype)


@pytest.mark.coalesce
@pytest.mark.parametrize("nnd, nnz, size", COO_CASES)
@pytest.mark.parametrize("dtype", CASES_DTYPES)
def test_accuracy_coalesce(nnd, nnz, size, dtype):
    """Structural equality against native for the full dtype sweep."""
    inp = _make_coo(nnd, nnz, size, dtype, flag_gems.device, seed=3)
    ref_inp = _make_coo(nnd, nnz, size, dtype, flag_gems.device, seed=3)
    # ``to_reference`` converts the whole object once; the reference is never
    # re-derived from a separately converted copy (the quick-cpu phase turns
    # the pair into two unrelated CPU tensors).
    ref_inp = utils.to_reference(ref_inp)

    assert inp.is_coalesced() is False
    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    _assert_same_structure(res, ref_out, dtype)
    # The input is never mutated by the fresh path.
    assert inp.is_coalesced() is False
    assert inp._nnz() == nnz
    assert res is not inp


@pytest.mark.coalesce
@pytest.mark.parametrize(
    "size", [(4, 5)] if QUICK_MODE else [(4, 5), (16, 16), (8, 8, 4)]
)
def test_accuracy_coalesce_duplicate_accumulation(size):
    """Duplicate columns with known values: the output value must be the sum.

    A dense reference is built from the *same* input tensors so the expected
    sums are computed by torch itself (``to_dense``) instead of by re-deriving
    the index arithmetic in the test.
    """
    nnd = len(size)
    inp = _make_coo(nnd, 40, size, torch.float32, flag_gems.device, seed=5)
    # Force at least one guaranteed duplicate pair on the first two entries.
    # The mutation happens BEFORE ``to_reference``: under --ref=cpu that call
    # deep-copies, so a mutation applied afterwards would only affect the
    # implementation side and the two sides would compare different tensors.
    idx = inp._indices()
    idx[:, 1] = idx[:, 0]
    vals = inp._values()
    vals[1] = vals[0]
    inp = torch.sparse_coo_tensor(idx, vals, size)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    _assert_same_structure(res, ref_out, torch.float32)
    # Whole-tensor check: the dense form must be identical, which catches both
    # a wrong group sum and a wrong sorted position.
    utils.gems_assert_close(res.to_dense(), ref_out.to_dense(), torch.float32)

    # The input is never mutated by the fresh path.
    assert inp.is_coalesced() is False
    assert inp._nnz() == 40
    assert res is not inp


@pytest.mark.coalesce
@pytest.mark.parametrize(
    "dtype",
    (
        [torch.float32, torch.bool]
        if QUICK_MODE
        else [torch.float32, torch.float64, torch.int64, torch.bool]
    ),
)
def test_accuracy_coalesce_large_nnz_above_small_path_ceiling(dtype):
    """nnz > 1024 must produce exactly native's entries for EVERY dtype.

    The small path serves fp64/ints/bool in a single program with
    BLOCK = 1024 lanes: before the scan-path rerouting, an input with more
    than 1024 stored entries lost everything past the 1024th (and collapsed
    positions, so the surviving values were wrong too). The case is built
    with duplicate coordinates (drawn with replacement) so the merge branch
    is exercised on both sides, and the full indices/values comparison is
    asserted, not just the entry count.
    """
    inp = _make_coo(2, 2000, (128, 128), dtype, flag_gems.device, seed=21)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    # The ceiling must actually have been crossed: with 2000 draws over
    # 16384 cells the output cannot collapse to <= 1024 entries.
    assert ref_out._nnz() > 1024
    _assert_same_structure(res, ref_out, dtype)


@pytest.mark.coalesce
def test_accuracy_coalesce_large_nnz_duplicate_accumulation_int64():
    """Large-nnz int64 with known duplicate sums, checked whole-tensor.

    Complements the structural sweep above with an explicit accumulation
    check on the scan path's int64 branch: the dense form of the coalesced
    result must equal the dense form native produces, which catches both a
    dropped entry and a wrong group sum.
    """
    inp = _make_coo(2, 2000, (128, 128), torch.int64, flag_gems.device, seed=23)
    idx = inp._indices()
    idx[:, 7] = idx[:, 3]
    vals = inp._values()
    vals[7] = 3
    inp = torch.sparse_coo_tensor(idx, vals, (128, 128))
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    assert res._nnz() == ref_out._nnz()
    assert res._nnz() > 1024
    utils.gems_assert_equal(res._indices(), ref_out._indices())
    utils.gems_assert_close(res._values(), ref_out._values(), torch.int64)
    utils.gems_assert_close(res.to_dense(), ref_out.to_dense(), torch.int64)


@pytest.mark.coalesce
def test_accuracy_coalesce_float32_large_nnz_exact():
    """float32 above the ceiling: multi-program grid must not truncate.

    The float path's grids scale with nnz (``cdiv(n, B)``), so it was never
    truncated; this case pins that property across the rerouting change so a
    future single-program regression on the float path cannot pass silently.
    """
    inp = _make_coo(2, 5000, (256, 256), torch.float32, flag_gems.device, seed=25)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    assert ref_out._nnz() > 1024
    _assert_same_structure(res, ref_out, torch.float32)


@pytest.mark.coalesce
@pytest.mark.parametrize("dtype", [torch.float32, torch.int64])
def test_accuracy_coalesce_identity_paths(dtype):
    """Already-coalesced and zero-nnz inputs must return the *same object*."""
    # 1. already coalesced -> identity
    inp = _make_coo(2, 12, (6, 6), dtype, flag_gems.device, seed=7).coalesce()
    assert inp.is_coalesced() is True
    ref_inp = utils.to_reference(inp)
    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)
    assert res is inp
    assert ref_out is ref_inp
    assert res.is_coalesced() == ref_out.is_coalesced()

    # 2. zero nnz -> native reports is_coalesced() == True -> identity
    empty = torch.sparse_coo_tensor(
        torch.empty((2, 0), dtype=torch.int64, device=flag_gems.device),
        torch.empty(0, dtype=dtype, device=flag_gems.device),
        (6, 6),
    )
    assert empty.is_coalesced() is True
    ref_empty = utils.to_reference(empty)
    assert ref_empty.coalesce() is ref_empty
    res_empty = flag_gems.coalesce(empty)
    assert res_empty is empty
    assert res_empty._nnz() == 0


@pytest.mark.coalesce
def test_accuracy_coalesce_single_entry():
    """nnz == 1 with duplicates impossible: sorted output, flag flipped."""
    inp = torch.sparse_coo_tensor(
        torch.tensor([[2], [3]], dtype=torch.int64, device=flag_gems.device),
        torch.tensor([9.0], device=flag_gems.device),
        (4, 4),
    )
    inp._coalesced_(False)
    ref_inp = utils.to_reference(inp)
    assert ref_inp.is_coalesced() is False

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    assert res is not inp
    _assert_same_structure(res, ref_out, torch.float32)
    assert res._values().tolist() == [9.0]


@pytest.mark.coalesce
def test_accuracy_coalesce_hybrid_dense_dims_unsupported():
    """Hybrid COO (values with dense trailing dims) is an explicit limitation.

    Native adds whole value rows for duplicate columns (measured,
    runs/coalesce/probe_native_cpu.log: duplicate hybrid columns fold to the
    row-wise sum). The supplied kernels accumulate 1-D value arrays only —
    they read ``val_ptr + entry_index`` (the first dense column) and build a
    1-D output value tensor, which ``torch.sparse_coo_tensor`` rejects for a
    shape with dense dims. The implementation rejects the input with
    NotImplementedError instead of silently producing wrong values; the
    exception CLASS is the contract asserted (never the message text).
    """
    hidx = torch.tensor(
        [[0, 1, 1, 0], [2, 0, 2, 2]], dtype=torch.int64, device=flag_gems.device
    )
    hval = torch.arange(8.0, device=flag_gems.device).reshape(4, 2)
    inp = torch.sparse_coo_tensor(hidx, hval, (3, 3, 2))
    ref_inp = utils.to_reference(inp)
    assert inp.dense_dim() == 1

    ref_out = ref_inp.coalesce()
    assert ref_out._nnz() == 3

    with pytest.raises(NotImplementedError):
        flag_gems.coalesce(inp)


@pytest.mark.coalesce
@pytest.mark.parametrize("size", [(4, 5)] if QUICK_MODE else [(4, 5), (5, 7, 9)])
def test_accuracy_coalesce_all_duplicates_and_dtype_preservation(size):
    """Every entry maps to one column pair: nnz collapses to the index count.

    Also pins the output dtype (each accumulation branch: fp32 for the float
    path, fp64/int64/int32 for the small path).
    """
    nnd = len(size)
    for dtype in (
        [torch.float32, torch.int32]
        if QUICK_MODE
        else [torch.float32, torch.float16, torch.float64, torch.int32, torch.int64]
    ):
        idx = torch.zeros((nnd, 8), dtype=torch.int64)
        idx[0, 4:] = 1  # two distinct columns, four duplicates each
        idx = idx.to(flag_gems.device)
        vals = torch.ones(8, dtype=dtype, device=flag_gems.device)
        inp = torch.sparse_coo_tensor(idx, vals, size)
        ref_inp = utils.to_reference(inp)

        ref_out = ref_inp.coalesce()
        res = flag_gems.coalesce(inp)

        assert res.dtype == ref_out.dtype
        assert res.dtype == dtype
        assert res._nnz() == 2
        assert res._nnz() == ref_out._nnz()
        assert res._indices().tolist() == ref_out._indices().tolist()
        utils.gems_assert_close(res._values(), ref_out._values(), dtype)


@pytest.mark.coalesce
@pytest.mark.parametrize(
    "layout_name, layout_enum",
    (
        [("dense", "Strided")]
        if QUICK_MODE
        else [("dense", "Strided"), ("csr", "SparseCsr"), ("bsc", "SparseBsc")]
    ),
)
def test_accuracy_coalesce_rejects_non_coo(layout_name, layout_enum):
    """Non-COO layouts are rejected by the implementation with RuntimeError.

    The exception CLASS is the assertion; the message fragment asserted is the
    layout enum name, which the implementation renders itself (measured on the
    GPU probe, runs/coalesce/probe_dispatch_gpu.log). Full-sentence wording is
    deliberately NOT pinned: CI's torch build is not the integration
    container's build and the reference's own sentence can differ.
    """
    base = torch.randn(4, 4, device=flag_gems.device)
    if layout_name == "dense":
        bad = base
    elif layout_name == "csr":
        bad = base.to_sparse_csr()
    else:
        bad = base.to_sparse_bsc((2, 2))

    ref_bad = utils.to_reference(bad)
    ref_raised = False
    try:
        ref_bad.coalesce()
    except RuntimeError:
        ref_raised = True
    assert ref_raised, f"native coalesce should reject the {layout_name} layout"

    with pytest.raises(RuntimeError) as excinfo:
        flag_gems.coalesce(bad)
    assert layout_enum in str(excinfo.value)


@pytest.mark.coalesce
def test_accuracy_coalesce_input_not_mutated():
    """The fresh path must not modify the input's data or coalesced flag."""
    inp = _make_coo(2, 24, (8, 8), torch.float32, flag_gems.device, seed=11)
    # ``to_reference`` copies the whole object once, so the pre-call snapshot
    # must be taken from the REFERENCE copy: under --ref=cpu the
    # implementation-side tensor stays on the accelerator and comparing its
    # live data against an accelerator-side clone would trip the device check
    # inside ``gems_assert_equal``.
    ref_inp = utils.to_reference(inp)
    ref_idx_before = ref_inp._indices().clone()
    ref_val_before = ref_inp._values().clone()

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    assert inp.is_coalesced() is False
    assert inp.is_coalesced() == ref_inp.is_coalesced()
    utils.gems_assert_equal(ref_inp._indices(), ref_idx_before)
    utils.gems_assert_close(ref_inp._values(), ref_val_before, torch.float32)
    _assert_same_structure(res, ref_out, torch.float32)


@pytest.mark.coalesce
def test_accuracy_coalesce_1d_sparse():
    """1-D sparse COO: sparse_dim == 1, index array is a single row."""
    inp = _make_coo(1, 20, (16,), torch.int32, flag_gems.device, seed=13)
    ref_inp = utils.to_reference(inp)

    ref_out = ref_inp.coalesce()
    res = flag_gems.coalesce(inp)

    assert res.sparse_dim() == 1
    assert res.sparse_dim() == ref_out.sparse_dim()
    _assert_same_structure(res, ref_out, torch.int32)


@pytest.mark.coalesce
def test_accuracy_coalesce_packet_call_forms():
    """Both call forms and the packet overload reach the submitted code."""
    inp = _make_coo(2, 16, (6, 6), torch.float32, flag_gems.device, seed=17)
    ref_inp = utils.to_reference(inp)
    ref_out = ref_inp.coalesce()

    res_packet = flag_gems.coalesce(inp)
    res_aten = torch.ops.aten.coalesce.default(ref_inp)
    _assert_same_structure(res_packet, ref_out, torch.float32)
    _assert_same_structure(res_aten, ref_out, torch.float32)


@pytest.mark.coalesce
def test_accuracy_coalesce_repeated_and_stable():
    """Repeated dispatch on the same input is stable and side-effect free."""
    inp = _make_coo(2, 32, (8, 8), torch.float32, flag_gems.device, seed=19)
    ref_inp = utils.to_reference(inp)
    ref_out = ref_inp.coalesce()

    for _ in range(3):
        res = flag_gems.coalesce(inp)
        _assert_same_structure(res, ref_out, torch.float32)
        assert inp.is_coalesced() is False
