# Copyright 2026 The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import threading

import numpy as np
import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

# Exact double constant equal to float32(0.000061): the reference scale floor
# (``SMALL_SCALE_THRESHOLD`` in the reference quant utils).
_SCALE_FLOOR = float.fromhex("0x1.ffb4800000000p-15")

_BLOCK = 1024
_MAX_PROGRAMS = 1024
_NUM_WARPS = 4
_MAX_GRAPHS = 16

# Reusable per-device scratch buffers (fully rewritten on every call; no input
# data is cached across calls) -- by *one call at a time*. The partial-min/max
# slots, the arrival counter, the packed result and the completion flag are all
# single-valued module state, so two threads entering the contiguous path at the
# same time would overwrite each other's partials and could steal each other's
# flag. Measured on the H20 build: two threads on two streams corrupt the result
# (a mismatching reduction, or a lost flag that makes the host spin for ever).
# The lock below makes the whole contiguous call -- launch, host spin and flag
# reset -- mutually exclusive, and is the reason the path is thread-safe.
# Measured with the lock: 25 rounds x 2 threads on 2 streams, zero mismatches
# and zero errors.
_call_lock = threading.Lock()

# Per-device scratch buffers, populated on first use.
_buffers = {}

# CUDA-graph replay cache keyed by (device, data_ptr, numel, dtype).
# Entry: [graph_or_None, sighting_count]
_graph_cache = {}

# Native ``aten::_choose_qparams_per_tensor`` is a CompositeImplicitAutograd
# ("math") kernel, not a device kernel, so the input has to be handled
# separately when no device launch is possible (the module item_data_ptr is
# null, or the tensor is not on the accelerator this backend drives). The hub
# below redispatches onto that math kernel, which is exactly what the
# unregistered dispatcher would have run.
_NATIVE_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeImplicitAutograd
)

# Dtype families native's ``min()``/``max()`` reduction rejects outright
# (measured on the H20 build: ``RuntimeError`` for every float8 variant and
# for complex), while a Triton kernel would happily stream them. Delegating
# keeps the caller on native's own error, wherever it comes from.
_NATIVE_UNSUPPORTED_DTYPES = frozenset(
    (
        torch.float8_e4m3fn,
        torch.float8_e4m3fnuz,
        torch.float8_e5m2,
        torch.float8_e5m2fnuz,
    )
)


def _native_fallback(self, reduce_range):
    return torch.ops.aten._choose_qparams_per_tensor.default.redispatch(
        _NATIVE_FALLBACK_KEYSET, self, reduce_range
    )


def _get_buffers(dev):
    b = _buffers.get(dev)
    if b is None:
        pmn = torch.empty(_MAX_PROGRAMS, dtype=torch.float32, device=dev)
        pmx = torch.empty(_MAX_PROGRAMS, dtype=torch.float32, device=dev)
        counter = torch.zeros(1, dtype=torch.int32, device=dev)
        # pinned host-mapped output and completion flag: the kernel writes the
        # packed min/max directly to host-visible memory (valid device address
        # via UVA), then raises the flag; the host spins on the flag and reads
        # the result with no D2H copy and no stream query.
        out = torch.empty(1, dtype=torch.int64, pin_memory=True)
        out_np = out.numpy().view(np.float32)
        flag = torch.zeros(1, dtype=torch.int32, pin_memory=True)
        flag_np = flag.numpy()
        b = (pmn, pmx, counter, out, out_np, flag, flag_np)
        _buffers[dev] = b
    return b


@triton.jit
def _minmax_fused_kernel(
    x_ptr,
    pmn_ptr,
    pmx_ptr,
    counter_ptr,
    out_ptr,
    flag_ptr,
    n_elements,
    n_partials,
    BLOCK: tl.constexpr,
    RBLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    num_pids = tl.num_programs(0)
    vmin = tl.full((BLOCK,), float("inf"), tl.float32)
    vmax = tl.full((BLOCK,), float("-inf"), tl.float32)

    n_full = n_elements - (n_elements % BLOCK)
    step = num_pids * BLOCK
    for start in range(pid * BLOCK, n_full, step):
        offs = start + tl.arange(0, BLOCK)
        x = tl.load(x_ptr + offs).to(tl.float32)
        vmin = tl.minimum(vmin, x)
        vmax = tl.maximum(vmax, x)

    # tail block (only program 0)
    if pid == 0:
        rem = n_elements - n_full
        if rem > 0:
            offs = n_full + tl.arange(0, BLOCK)
            mask = offs < n_elements
            x = tl.load(x_ptr + offs, mask=mask, other=0.0).to(tl.float32)
            xm = tl.where(mask, x, float("inf"))
            xM = tl.where(mask, x, float("-inf"))
            vmin = tl.minimum(vmin, xm)
            vmax = tl.maximum(vmax, xM)

    mn = tl.min(vmin, axis=0)
    mx = tl.max(vmax, axis=0)
    tl.store(pmn_ptr + pid, mn)
    tl.store(pmx_ptr + pid, mx)

    old = tl.atomic_add(counter_ptr, 1, sem="acq_rel")
    if old == n_partials - 1:
        # last arrival: reduce all partials and emit the packed result
        roffs = tl.arange(0, RBLOCK)
        rmask = roffs < n_partials
        pmn = tl.load(pmn_ptr + roffs, mask=rmask, other=float("inf"))
        pmx = tl.load(pmx_ptr + roffs, mask=rmask, other=float("-inf"))
        fmn = tl.min(pmn, axis=0)
        fmx = tl.max(pmx, axis=0)
        bmin = fmn.to(tl.int32, bitcast=True)
        bmax = fmx.to(tl.int32, bitcast=True)
        packed = (bmax.to(tl.int64) << 32) | (bmin.to(tl.int64) & 0xFFFFFFFF)
        tl.store(out_ptr, packed)
        # release-ordered completion flag, then reset the arrival counter
        tl.atomic_xchg(flag_ptr, 1, sem="release")
        tl.atomic_xchg(counter_ptr, 0, sem="release")


@triton.jit
def _minmax_strided_kernel(
    x_ptr,
    mn_ptr,
    mx_ptr,
    n_elements,
    shape_ptr,
    stride_ptr,
    ndim,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    num_pids = tl.num_programs(0)
    vmin = tl.full((BLOCK,), float("inf"), tl.float32)
    vmax = tl.full((BLOCK,), float("-inf"), tl.float32)
    step = num_pids * BLOCK
    for base in range(pid * BLOCK, n_elements, step):
        idx = base + tl.arange(0, BLOCK)
        mask = idx < n_elements
        off = tl.zeros((BLOCK,), dtype=tl.int64)
        rem = idx
        for d in range(ndim - 1, -1, -1):
            s = tl.load(shape_ptr + d)
            st = tl.load(stride_ptr + d)
            c = rem % s
            off += c * st
            rem = rem // s
        x = tl.load(x_ptr + off, mask=mask, other=0.0).to(tl.float32)
        xm = tl.where(mask, x, float("inf"))
        xM = tl.where(mask, x, float("-inf"))
        vmin = tl.minimum(vmin, xm)
        vmax = tl.maximum(vmax, xM)
    tl.atomic_min(mn_ptr, tl.min(vmin, axis=0))
    tl.atomic_max(mx_ptr, tl.max(vmax, axis=0))


def _launch_fused(x, pmn, pmx, counter, out, flag, n, n_progs, BLOCK, nw):
    _minmax_fused_kernel[(n_progs,)](
        x,
        pmn,
        pmx,
        counter,
        out,
        flag,
        n,
        n_progs,
        BLOCK=BLOCK,
        RBLOCK=_MAX_PROGRAMS,
        num_warps=nw,
    )


def _capture_fused(x, pmn, pmx, counter, out, flag, n, n_progs, BLOCK, nw):
    # Capture is only entered from the plain-launch branch, and only after the
    # caller has been cleared of holding a capture (see the caller).
    g = torch.cuda.CUDAGraph()
    # ``capture_error_mode="thread_local"``: torch.cuda.graph's default
    # "global" mode makes the capture forbid potentially-unsafe calls
    # *process-wide* -- a ``.item()``/stream sync issued by another thread
    # (here: the non-contiguous path's ``out2[0].item()``) errors with
    # "operation not permitted when stream is capturing" and poisons every
    # concurrent caller with a sticky CUDA error. Measured (H20, mixed
    # contiguous + non-contiguous threads): with the default mode a single
    # capture window kills four concurrent workers; with "thread_local" the
    # capture only constrains the capturing thread, which is the scope the
    # module lock already serializes. Scratch-buffer safety is unaffected:
    # the lock below still serializes every contiguous call, and the
    # non-contiguous path keeps its own per-call buffers.
    with torch.cuda.graph(g, capture_error_mode="thread_local"):
        _launch_fused(x, pmn, pmx, counter, out, flag, n, n_progs, BLOCK, nw)
    return g


def _choose_qparams_per_tensor(self, reduce_range=False):
    """Return the affine quantization parameters of ``self``.

    Mirrors ``aten::_choose_qparams_per_tensor(Tensor self, bool
    reduce_range=False) -> (float, int)``: a plain ``(scale, zero_point)``
    Python tuple, ``scale`` a Python float and ``zero_point`` a Python int.

    Two kernels are used. The contiguous path streams the tensor with a fused
    min/max kernel whose last program packs the two float32 results into one
    int64, writes them to pinned host memory and raises a release-ordered
    completion flag; the caller spins on that flag instead of synchronizing the
    device. The non-contiguous path walks the logical index space through an
    int32 shape/stride table with int64 offsets: each per-axis term is
    accumulated into an int64 ``off``, so an offset whose *sum* exceeds
    ``2**31`` is still walked correctly. The table is int32 rather than int64
    because the kernel's loop-carried ``rem`` (``rem = idx``) is int32 and
    Triton rejects the loop when an int64 load re-types it; a size or stride
    at or above ``2**31`` therefore fails when the table is built. The
    reduction itself uses ``atomic_min``/``atomic_max``.

    The ``(scale, zero_point)`` arithmetic that follows the reduction is the
    reference one, in float32: ``scale = (max(max, 0) - min(min, 0)) / qmax``
    with ``qmax = 127`` when ``reduce_range`` else ``255``, floored at
    ``float32(0.000061)``; a zero raw scale becomes ``(0.1, 0)``; otherwise
    ``zero_point = -round(min(min, 0) / scale_raw)`` clamped to ``[0, qmax]``.

    Documented, measured differences from the native operator on the H20 build
    (``torch 2.8.0a0+5228986c39.nv25.05``); the tests pin each of them on both
    sides rather than pretending they agree:

    - Subnormal ranges. Native replaces the scale with the fixed ``0.1`` when
      the float32 reciprocal of the raw scale is infinite (``[0, x]`` with
      ``x`` below ~``1.2e-38``), while the reference formula only floors at the
      small-scale threshold. Measured on ``[0, 1e-38]``: native
      ``(0.1, 0)``, this implementation ``(6.0999998822808266e-05, 0)``; the
      boundary sits between ``1e-37`` and ``1e-36``, where both sides return
      the floor again. The contiguous and non-contiguous paths of this
      implementation agree with *each other* across the whole window.
    - ``inf`` input: native returns ``scale = inf`` with ``zero_point``
      ``-2**31`` for a positive-infinite maximum, but the clamp (``qmax``) for
      a negative-infinite minimum, since only the latter reaches native's
      clamp. A finite maximum with ``min = -inf`` is answered ``(inf, qmax)``
      here as well; the reference formula would instead compute ``inf / inf``
      -> NaN and fail on ``round(nan)``. Native's NaN input raises
      ``RuntimeError: In ChooseQuantizationParams, min should be less than or
      equal to max`` and is not matched. All of this is pinned by the tests.
    - A tensor with no device storage (``meta``, whose ``data_ptr()`` is 0), a
      host tensor, a float8/complex dtype, or a sparse layout cannot be
      launched on (or must be answered by native's own rejection); those
      inputs are delegated to the native math kernel unchanged, so native's
      own behaviour is what the caller sees. Without the delegation the
      pinned-flag spin would never terminate for a meta tensor (measured: a
      meta tensor hung the caller past a 30 s probe timeout), a float8 tensor
      would get numbers where native raises, and a CPU tensor would fail
      inside the launcher instead of reproducing native's answer.
    - ``reduce_range`` is dropped by native when the quantization engine is
      QNNPACK (``qengine() == QNNPACK``); this implementation always honours
      the argument. The default engine on this build is ``x86``, where the two
      agree.
    - Thread safety and capture are this implementation's own concern, not
      native's: see ``_call_lock`` and the capture guard in the contiguous
      branch.
    """
    logger.debug("GEMS _CHOOSE_QPARAMS_PER_TENSOR")
    try:
        device_context = torch_device_fn.device(self.device)
    except Exception:
        # Not a device this backend can launch on (meta, or a host tensor):
        # hand the call back to the native math kernel.
        return _native_fallback(self, reduce_range)

    dev = self.device
    with device_context:
        # A storage-less tensor has numel > 0 but a null item data pointer;
        # launching on it would leave the completion flag unset for ever.
        # Float8 and complex dtypes are delegated too: native rejects both
        # (``RuntimeError`` from its min()/max() or dtype checks) and must not
        # be answered with numbers (float8, measured: source returned
        # (0.0117, 170) where native raises) or a foreign error class.
        if (
            self.layout != torch.strided
            or self.data_ptr() == 0
            or self.dtype in _NATIVE_UNSUPPORTED_DTYPES
            or self.dtype.is_complex
        ):
            return _native_fallback(self, reduce_range)

        n = self.numel()
        if n == 0:
            # Mirrors the source implementation's explicit empty-input guard.
            # Native raises the same error from its own ``min()`` call; the
            # integration container's build emits this exact sentence, and CI
            # runs a different build, so the tests assert the class plus the
            # semantic fragments (``min()``, ``dim``, ``numel() == 0``) rather
            # than the whole string.
            raise RuntimeError(
                "min(): Expected reduction dim to be specified for "
                "input.numel() == 0."
            )

        if self.is_contiguous():
            # A launch recorded inside someone else's CUDA capture is not
            # *executed* (measured: the completion flag never rises), so the
            # host spin below would wait for ever. Native has the same
            # limitation -- ``min().item()`` cannot be captured either -- so the
            # call is handed back to the native math kernel, which reports the
            # capture error to the caller exactly as it would without this
            # registration. This is the same "no launch possible here"
            # delegation as the meta/host guard above.
            if torch.cuda.is_current_stream_capturing():
                return _native_fallback(self, reduce_range)

            pmn, pmx, counter, out, out_np, flag, flag_np = _get_buffers(dev)
            # Larger blocks / fewer programs for big tensors: identical
            # streaming throughput with less device-side block-launch overhead.
            if n >= 1048576:
                BLOCK = 2048
                gridcap = 512
                nw = 4
            else:
                BLOCK = _BLOCK
                gridcap = _MAX_PROGRAMS
                nw = _NUM_WARPS
            n_progs = min((n + BLOCK - 1) // BLOCK, gridcap)
            # The scratch buffers hold one call's partials, arrival counter,
            # packed result and completion flag at a time, so the whole
            # contiguous call -- launch, host spin and flag reset -- runs under
            # the module lock. Measured before the lock: two threads on two
            # streams corrupt each other's reduction, because each writes its
            # own partials into the same slots and the last arrival of either
            # kernel resets the shared counter for both.
            with _call_lock:
                key = (dev, self.data_ptr(), n, self.dtype)
                entry = _graph_cache.get(key)
                if entry is None:
                    _launch_fused(
                        self, pmn, pmx, counter, out, flag, n, n_progs, BLOCK, nw
                    )
                    _graph_cache[key] = [None, 1]
                else:
                    g, count = entry
                    if count >= 2:
                        g.replay()
                    else:
                        g = _capture_fused(
                            self, pmn, pmx, counter, out, flag, n, n_progs, BLOCK, nw
                        )
                        if len(_graph_cache) > _MAX_GRAPHS:
                            _graph_cache.pop(next(iter(_graph_cache)))
                        _graph_cache[key] = [g, count + 1]
                        g.replay()
                # spin on the release-ordered completion flag (pinned host
                # memory). This is the source design: no D2H copy and no stream
                # query. The guards above are what keep it from spinning for
                # ever -- every input that can reach this point launches a
                # kernel that raises the flag.
                while flag_np[0] == 0:
                    pass
                mn = float(out_np[0])
                mx = float(out_np[1])
                flag_np[0] = 0
        else:
            out2 = torch.tensor(
                [float("inf"), float("-inf")], device=dev, dtype=torch.float32
            )
            shape_t = torch.tensor(self.shape, device=dev, dtype=torch.int32)
            stride_t = torch.tensor(self.stride(), device=dev, dtype=torch.int32)
            n_progs = min((n + _BLOCK - 1) // _BLOCK, _MAX_PROGRAMS)
            _minmax_strided_kernel[(n_progs,)](
                self,
                out2,
                out2[1:],
                n,
                shape_t,
                stride_t,
                self.dim(),
                BLOCK=_BLOCK,
                num_warps=_NUM_WARPS,
            )
            mn = float(out2[0].item())
            mx = float(out2[1].item())

    qmax = 127 if reduce_range else 255
    mn_neg = mn if mn < 0.0 else 0.0
    mx_pos = mx if mx > 0.0 else 0.0
    scale_raw = (mx_pos - mn_neg) / float(qmax)

    if scale_raw == 0.0:
        scale = 0.1
        zero_point = 0
    else:
        # A negative-only infinite range makes ``scale_raw`` +inf, so the
        # reference ``-round(mn_neg / scale_raw)`` below is ``-round(nan)`` and
        # raises ``ValueError``. Native answers ``(inf, qmax)`` here, so return
        # that instead of crashing. (``mn_neg`` is the only negative term, so
        # ``scale_raw`` is +inf exactly when the range is infinite.)
        if np.isinf(scale_raw) and mn_neg < 0.0:
            return (float("inf"), qmax)
        if scale_raw < _SCALE_FLOOR:
            scale = _SCALE_FLOOR
        else:
            scale = scale_raw
        zero_point = -round(mn_neg / scale_raw)
        if zero_point < 0:
            zero_point = 0
        if zero_point > qmax:
            zero_point = qmax

    return (scale, zero_point)
