# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""chain_matmul in Triton.

Computes the product of a chain of 2-D matrices using an optimal (minimum-flop)
parenthesization, mirroring torch.linalg.multi_dot / aten::chain_matmul
semantics. Every matmul is computed by a Triton device kernel; the host wrapper
only allocates intermediates, computes the grid, and launches JIT kernels.

Numerical strategy:
- fp32 inputs: emulated fp32 via 3 fp16 tensor-core dots (hi/lo split). Each
  fp16 product is exact and fp32 accumulation is preserved; dropped lo*lo terms
  are ~2^-22 relative, far inside the FlagGems gate (atol=5e-4*K vs fp64 ref).
- fp16/bf16 inputs: native tensor-core dot (wgmma k16) with fp32 accumulation.
- fp64 inputs: cast to fp32 in-kernel, computed via the same fp16-split path,
  stored back as fp64. Gate atol=5e-4*K dominates; error stays ~1e-5.

Block configs are tuned per gemm shape class from on-target sweeps (H800).
Tiny 3-matrix chains (all dims <= 16) run in one fused single-program kernel;
fp16/bf16 4-matrix chains of the form A@(B@(C@D)) fuse the last two gemms.
"""

from __future__ import annotations

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Fused last-two-gemm kernel: out = A @ F with F = B @ E (register resident)
# Used for fp16/bf16 chains where the F intermediate is <= 128x64.
# ---------------------------------------------------------------------------
@triton.jit
def _mm_last2_kernel(
    b_ptr,
    e_ptr,
    a_ptr,
    out_ptr,
    M_F,
    K_B,
    N_E,
    M_O,
    stride_bm,
    stride_bk,
    stride_ek,
    stride_en,
    stride_am,
    stride_ak,
    stride_om,
    stride_on,
    BLOCK_MF: tl.constexpr,
    BLOCK_NE: tl.constexpr,
    BLOCK_K1: tl.constexpr,
    BLOCK_K2: tl.constexpr,
    BLOCK_MO: tl.constexpr,
    DT: tl.constexpr,
):
    offs_mf = tl.arange(0, BLOCK_MF)
    offs_ne = tl.arange(0, BLOCK_NE)
    offs_k1 = tl.arange(0, BLOCK_K1)
    F = tl.zeros((BLOCK_MF, BLOCK_NE), dtype=tl.float32)
    b_ptrs = b_ptr + offs_mf[:, None] * stride_bm + offs_k1[None, :] * stride_bk
    e_ptrs = e_ptr + offs_k1[:, None] * stride_ek + offs_ne[None, :] * stride_en
    for k in range(0, tl.cdiv(K_B, BLOCK_K1)):
        k_offs = k * BLOCK_K1 + offs_k1
        b = tl.load(
            b_ptrs,
            mask=(offs_mf[:, None] < M_F) & (k_offs[None, :] < K_B),
            other=0.0,
        )
        e = tl.load(
            e_ptrs,
            mask=(k_offs[:, None] < K_B) & (offs_ne[None, :] < N_E),
            other=0.0,
        )
        F = tl.dot(b, e, F)
        b_ptrs += BLOCK_K1 * stride_bk
        e_ptrs += BLOCK_K1 * stride_ek

    offs_mo = tl.arange(0, BLOCK_MO)
    offs_k2 = tl.arange(0, BLOCK_K2)
    a = tl.load(
        a_ptr + offs_mo[:, None] * stride_am + offs_k2[None, :] * stride_ak,
        mask=(offs_mo[:, None] < M_O) & (offs_k2[None, :] < M_F),
        other=0.0,
    )
    out = tl.zeros((BLOCK_MO, BLOCK_NE), dtype=tl.float32)
    if DT == 16:
        out = tl.dot(a, F.to(a_ptr.dtype.element_ty), out)
    else:
        a_hi = a.to(tl.float16)
        f_hi = F.to(tl.float16)
        a_lo = (a - a_hi.to(tl.float32)).to(tl.float16)
        f_lo = (F - f_hi.to(tl.float32)).to(tl.float16)
        out = tl.dot(a_hi, f_hi, out)
        out = tl.dot(a_hi, f_lo, out)
        out = tl.dot(a_lo, f_hi, out)

    om = offs_mo[:, None] * stride_om + offs_ne[None, :] * stride_on
    mask = (offs_mo[:, None] < M_O) & (offs_ne[None, :] < N_E)
    if DT == 64:
        tl.store(out_ptr + om, out.to(tl.float64), mask=mask)
    else:
        tl.store(out_ptr + om, out.to(out_ptr.dtype.element_ty), mask=mask)


def _mm_last2(a, b, e):
    """out = A @ (B @ E) in one launch; A: (M_O x M_F), B: (M_F x K_B), E: (K_B x N_E)."""
    M_F, K_B = b.shape
    K_B2, N_E = e.shape
    M_O, K_A = a.shape
    dt = a.dtype
    out = torch.empty((M_O, N_E), device=a.device, dtype=dt)
    dtag = 64 if dt == torch.float64 else (32 if dt == torch.float32 else 16)
    _mm_last2_kernel[(1,)](
        b,
        e,
        a,
        out,
        M_F,
        K_B,
        N_E,
        M_O,
        b.stride(0),
        b.stride(1),
        e.stride(0),
        e.stride(1),
        a.stride(0),
        a.stride(1),
        out.stride(0),
        out.stride(1),
        BLOCK_MF=128,
        BLOCK_NE=64,
        BLOCK_K1=64,
        BLOCK_K2=128,
        BLOCK_MO=64,
        DT=dtag,
        num_warps=8,
        num_stages=2,
    )
    return out


# ---------------------------------------------------------------------------
# Fused single-launch kernel for tiny 3-matrix chains (all dims <= 16)
# out = (A @ B) @ C if LEFT else A @ (B @ C)
# ---------------------------------------------------------------------------
@triton.jit
def _chain3_kernel(
    a_ptr,
    b_ptr,
    c_ptr,
    out_ptr,
    M,
    K,
    K2,
    N,
    stride_am,
    stride_ak,
    stride_bk,
    stride_bk2,
    stride_ck2,
    stride_cn,
    stride_om,
    stride_on,
    BLOCK: tl.constexpr,
    LEFT: tl.constexpr,
    DT: tl.constexpr,
):
    offs_m = tl.arange(0, BLOCK)
    offs_k = tl.arange(0, BLOCK)
    offs_k2 = tl.arange(0, BLOCK)
    offs_n = tl.arange(0, BLOCK)

    if LEFT:
        a = tl.load(
            a_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak,
            mask=(offs_m[:, None] < M) & (offs_k[None, :] < K),
            other=0.0,
        )
        b = tl.load(
            b_ptr + offs_k[:, None] * stride_bk + offs_k2[None, :] * stride_bk2,
            mask=(offs_k[:, None] < K) & (offs_k2[None, :] < K2),
            other=0.0,
        )
        if DT == 64:
            a = a.to(tl.float32)
            b = b.to(tl.float32)
        d = tl.zeros((BLOCK, BLOCK), dtype=tl.float32)
        if DT == 32 or DT == 64:
            a_hi = a.to(tl.float16)
            b_hi = b.to(tl.float16)
            a_lo = (a - a_hi.to(tl.float32)).to(tl.float16)
            b_lo = (b - b_hi.to(tl.float32)).to(tl.float16)
            d = tl.dot(a_hi, b_hi, d)
            d = tl.dot(a_hi, b_lo, d)
            d = tl.dot(a_lo, b_hi, d)
        else:
            d = tl.dot(a, b, d)
        c = tl.load(
            c_ptr + offs_k2[:, None] * stride_ck2 + offs_n[None, :] * stride_cn,
            mask=(offs_k2[:, None] < K2) & (offs_n[None, :] < N),
            other=0.0,
        )
        out = tl.zeros((BLOCK, BLOCK), dtype=tl.float32)
        if DT == 16:
            out = tl.dot(d.to(b_ptr.dtype.element_ty), c, out)
        else:
            d_hi = d.to(tl.float16)
            c_hi = c.to(tl.float16)
            d_lo = (d - d_hi.to(tl.float32)).to(tl.float16)
            c_lo = (c - c_hi.to(tl.float32)).to(tl.float16)
            out = tl.dot(d_hi, c_hi, out)
            out = tl.dot(d_hi, c_lo, out)
            out = tl.dot(d_lo, c_hi, out)
    else:
        b = tl.load(
            b_ptr + offs_k[:, None] * stride_bk + offs_k2[None, :] * stride_bk2,
            mask=(offs_k[:, None] < K) & (offs_k2[None, :] < K2),
            other=0.0,
        )
        c = tl.load(
            c_ptr + offs_k2[:, None] * stride_ck2 + offs_n[None, :] * stride_cn,
            mask=(offs_k2[:, None] < K2) & (offs_n[None, :] < N),
            other=0.0,
        )
        if DT == 64:
            b = b.to(tl.float32)
            c = c.to(tl.float32)
        d = tl.zeros((BLOCK, BLOCK), dtype=tl.float32)
        if DT == 32 or DT == 64:
            b_hi = b.to(tl.float16)
            c_hi = c.to(tl.float16)
            b_lo = (b - b_hi.to(tl.float32)).to(tl.float16)
            c_lo = (c - c_hi.to(tl.float32)).to(tl.float16)
            d = tl.dot(b_hi, c_hi, d)
            d = tl.dot(b_hi, c_lo, d)
            d = tl.dot(b_lo, c_hi, d)
        else:
            d = tl.dot(b, c, d)
        a = tl.load(
            a_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak,
            mask=(offs_m[:, None] < M) & (offs_k[None, :] < K),
            other=0.0,
        )
        out = tl.zeros((BLOCK, BLOCK), dtype=tl.float32)
        if DT == 16:
            out = tl.dot(a, d.to(a_ptr.dtype.element_ty), out)
        else:
            a_hi = a.to(tl.float16)
            d_hi = d.to(tl.float16)
            a_lo = (a - a_hi.to(tl.float32)).to(tl.float16)
            d_lo = (d - d_hi.to(tl.float32)).to(tl.float16)
            out = tl.dot(a_hi, d_hi, out)
            out = tl.dot(a_hi, d_lo, out)
            out = tl.dot(a_lo, d_hi, out)

    om = offs_m[:, None] * stride_om + offs_n[None, :] * stride_on
    mask = (offs_m[:, None] < M) & (offs_n[None, :] < N)
    if DT == 64:
        tl.store(out_ptr + om, out.to(tl.float64), mask=mask)
    else:
        tl.store(out_ptr + om, out.to(out_ptr.dtype.element_ty), mask=mask)


def _chain3(a, b, c, left):
    M, K = a.shape
    K2, N = c.shape
    dt = a.dtype
    out = torch.empty((M, N), device=a.device, dtype=dt)
    if dt == torch.float64:
        dtag = 64
    elif dt == torch.float32:
        dtag = 32
    else:
        dtag = 16
    _chain3_kernel[(1,)](
        a,
        b,
        c,
        out,
        M,
        K,
        K2,
        N,
        a.stride(0),
        a.stride(1),
        b.stride(0),
        b.stride(1),
        c.stride(0),
        c.stride(1),
        out.stride(0),
        out.stride(1),
        BLOCK=16,
        LEFT=left,
        DT=dtag,
        num_warps=1,
        num_stages=1,
    )
    return out


# ---------------------------------------------------------------------------
# Triton matmul kernel (masked, stride-generic, group-swizzled)
# DT: 16 = fp16/bf16 native dot; 32 = fp32 via fp16 hi/lo split; 64 = fp64
# ---------------------------------------------------------------------------
@triton.jit
def _mm_kernel(
    a_ptr,
    b_ptr,
    c_ptr,
    M,
    N,
    K,
    stride_am,
    stride_ak,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
    GROUP_M: tl.constexpr,
    DT: tl.constexpr,
):
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_M)
    num_pid_n = tl.cdiv(N, BLOCK_N)
    num_pid_in_group = GROUP_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_M)
    pid_m = first_pid_m + (pid % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    a_ptrs = a_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak
    b_ptrs = b_ptr + offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for k in range(0, tl.cdiv(K, BLOCK_K)):
        k_offs = k * BLOCK_K + offs_k
        a_mask = (offs_m[:, None] < M) & (k_offs[None, :] < K)
        b_mask = (k_offs[:, None] < K) & (offs_n[None, :] < N)
        a = tl.load(a_ptrs, mask=a_mask, other=0.0)
        b = tl.load(b_ptrs, mask=b_mask, other=0.0)
        if DT == 64:
            a = a.to(tl.float32)
            b = b.to(tl.float32)
        if DT == 32 or DT == 64:
            # fp32 -> hi/lo fp16 split; 3 exact fp16 products accumulate in fp32
            a_hi = a.to(tl.float16)
            b_hi = b.to(tl.float16)
            a_lo = (a - a_hi.to(tl.float32)).to(tl.float16)
            b_lo = (b - b_hi.to(tl.float32)).to(tl.float16)
            acc = tl.dot(a_hi, b_hi, acc)
            acc = tl.dot(a_hi, b_lo, acc)
            acc = tl.dot(a_lo, b_hi, acc)
        else:
            acc = tl.dot(a, b, acc)
        a_ptrs += BLOCK_K * stride_ak
        b_ptrs += BLOCK_K * stride_bk

    offs_cm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_cn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    c_ptrs = c_ptr + offs_cm[:, None] * stride_cm + offs_cn[None, :] * stride_cn
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)
    if DT == 64:
        tl.store(c_ptrs, acc.to(tl.float64), mask=c_mask)
    else:
        tl.store(c_ptrs, acc.to(c_ptr.dtype.element_ty), mask=c_mask)


def _cfg_f16(M, N, K):
    """(BLOCK_M, BLOCK_N, BLOCK_K, num_warps, num_stages, GROUP_M) fp16/bf16."""
    if M >= 1024 and N >= 2048:
        return 128, 256, 64, 8, 4, 8
    if M >= 512 and N >= 2048:
        return 128, 128, 64, 8, 6, 8
    if K >= 2048 and N <= 512:
        return 64, 128, 64, 4, 4, 8
    if K >= 1024 and N >= 1024 and M >= 512:
        return 128, 128, 64, 8, 3, 8
    if M >= 256 and N >= 256 and K >= 256:
        return 64, 64, 128, 4, 3, 8
    if M >= 64 and N >= 64:
        return 64, 64, 64, 4, 4, 8
    if M >= 32 and N >= 32:
        return 32, 32, 64, 4, 3, 8
    return 16, 16, 32, 2, 2, 8


def _cfg_f32(M, N, K):
    """(BLOCK_M, BLOCK_N, BLOCK_K, num_warps, num_stages, GROUP_M) fp32 / fp64."""
    if M >= 1024 and N >= 2048:
        return 256, 128, 32, 8, 3, 4
    if M >= 512 and N >= 2048:
        return 128, 128, 64, 8, 4, 8
    if K >= 2048 and N <= 512:
        return 128, 128, 32, 8, 5, 8
    if K >= 1024 and N >= 1024 and M >= 512:
        return 256, 128, 32, 8, 3, 16
    if M >= 64 and N >= 64:
        return 32, 64, 64, 4, 3, 8
    if M >= 32 and N >= 32:
        return 32, 32, 64, 4, 3, 8
    return 16, 16, 32, 2, 2, 8


# Shape-class -> block-config memo. Every distinct (M, N, K, dtype) the process
# ever sees would add an entry for the life of the module, so the dict is
# bounded: FIFO eviction beyond _CFG_CACHE_MAX keeps memory flat while
# retaining every config a steady working set re-requests. The entries are tiny
# 7-tuples and the key is a 4-tuple, so the bound is a few hundred KiB at most.
_CFG_CACHE = {}
_CFG_CACHE_MAX = 4096


def _pick_config(M, N, K, dt):
    key = (M, N, K, dt)
    hit = _CFG_CACHE.get(key)
    if hit is not None:
        return hit
    if dt in (torch.float16, torch.bfloat16):
        bm, bn, bk, w, s, gm = _cfg_f16(M, N, K)
        hit = (bm, bn, bk, w, s, gm, 16)
    elif dt == torch.float32:
        bm, bn, bk, w, s, gm = _cfg_f32(M, N, K)
        hit = (bm, bn, bk, w, s, gm, 32)
    else:
        bm, bn, bk, w, s, gm = _cfg_f32(M, N, K)
        hit = (bm, bn, bk, w, s, gm, 64)
    if len(_CFG_CACHE) >= _CFG_CACHE_MAX:
        # Insertion-ordered dict: pop the oldest key (FIFO).
        _CFG_CACHE.pop(next(iter(_CFG_CACHE)))
    _CFG_CACHE[key] = hit
    return hit


def _mm(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    M, K = a.shape
    K2, N = b.shape
    dt = a.dtype
    c = torch.empty((M, N), device=a.device, dtype=dt)
    bm, bn, bk, warps, stages, gm, dtag = _pick_config(M, N, K, dt)
    grid = (triton.cdiv(M, bm) * triton.cdiv(N, bn),)
    with torch_device_fn.device(a.device):
        _mm_kernel[grid](
            a,
            b,
            c,
            M,
            N,
            K,
            a.stride(0),
            a.stride(1),
            b.stride(0),
            b.stride(1),
            c.stride(0),
            c.stride(1),
            BLOCK_M=bm,
            BLOCK_N=bn,
            BLOCK_K=bk,
            GROUP_M=gm,
            DT=dtag,
            num_warps=warps,
            num_stages=stages,
        )
    return c


# ---------------------------------------------------------------------------
# Optimal parenthesization (matrix-chain DP) + cached flat execution plan
# ---------------------------------------------------------------------------
_PLAN_CACHE = {}


def _compute_plan(dims):
    """Post-order list of (lhs, rhs) node indices; nodes 0..n-1 are inputs."""
    n = len(dims) - 1
    cost = [[0] * n for _ in range(n)]
    split = [[0] * n for _ in range(n)]
    for L in range(2, n + 1):
        for i in range(n - L + 1):
            j = i + L - 1
            best = None
            best_k = i
            for k in range(i, j):
                c = cost[i][k] + cost[k + 1][j] + dims[i] * dims[k + 1] * dims[j + 1]
                if best is None or c < best:
                    best = c
                    best_k = k
            cost[i][j] = best
            split[i][j] = best_k

    steps = []
    node_id = {}
    next_id = [n]

    def build(i, j):
        key = (i, j)
        if key in node_id:
            return node_id[key]
        if i == j:
            node_id[key] = i
            return i
        k = split[i][j]
        left = build(i, k)
        right = build(k + 1, j)
        node_id[key] = next_id[0]
        steps.append((left, right))
        next_id[0] += 1
        return node_id[key]

    build(0, n - 1)
    return steps


def _plan(dims):
    key = tuple(dims)
    plan = _PLAN_CACHE.get(key)
    if plan is None:
        plan = _compute_plan(key)
        _PLAN_CACHE[key] = plan
    return plan


def _check_matrices(matrices):
    """Mirror the native validation order of aten::chain_matmul / .out.

    Native order (measured on this build and matched to the ATen source of
    ``chain_matmul`` / ``chain_matmul_out``):
      1. every element must be 2-D        -> "Tensor dimension is {d}, expected 2 instead."
      2. the list must be non-empty       -> "chain_matmul(): Expected one or more matrices"
    For a single matrix the output is a clone / a copy into ``out``.
    The remaining 2-or-more checks are the ``multi_dot`` ones reused by native
    (dtype uniformity, shape compatibility), reproduced in the same order.
    """
    for i, m in enumerate(matrices):
        if m.dim() != 2:
            raise RuntimeError(f"Tensor dimension is {m.dim()}, expected 2 instead.")
    if len(matrices) == 0:
        raise RuntimeError("chain_matmul(): Expected one or more matrices")
    if len(matrices) == 1:
        return
    dtype = matrices[0].dtype
    device = matrices[0].device
    for i in range(1, len(matrices)):
        if matrices[i].dtype != dtype:
            raise RuntimeError(
                "multi_dot(): all tensors must have be the same dtype but "
                f"tensor 0 is {dtype} and tensor {i} {matrices[i].dtype}"
            )
        if matrices[i].device != device:
            raise RuntimeError(
                "multi_dot(): all tensors must be on the same device but "
                f"tensor 0 is on {device} and tensor {i} on {matrices[i].device}"
            )
        if matrices[i - 1].shape[-1] != matrices[i].shape[0]:
            raise RuntimeError(
                f"multi_dot(): tensors {i - 1} and {i} with shapes "
                f"{list(matrices[i - 1].shape)} and {list(matrices[i].shape)} "
                "cannot be multiplied"
            )


def _chain_matmul_impl(matrices):
    """Shared body of the default and ``.out`` overloads, mirrors native."""
    n = len(matrices)
    if n == 1:
        return matrices[0].clone()

    dims = [matrices[0].shape[0]] + [m.shape[1] for m in matrices]
    plan = _plan(dims)
    if n == 3 and max(dims) <= 16:
        return _chain3(matrices[0], matrices[1], matrices[2], plan[0] == (0, 1))
    # Fused path: fires only for the one 4-matrix parenthesization the DP
    # produces as ``A @ (B @ (C @ D))`` -- plan == [(2, 3), (1, 4), (0, 5)].
    # The plan predicate is what selects that DP shape; every other 4-matrix
    # plan (e.g. ``(A @ B) @ (C @ D)`` or a different split) falls through to
    # the general loop below and is computed by the plain ``_mm`` path. The
    # dtype/dimension guards that follow then decide whether the fused kernel
    # can hold the shapes, and otherwise fall through as well.
    if (
        n == 4
        and len(plan) == 3
        and plan[0] == (2, 3)
        and plan[1][0] == 1
        and plan[1][1] == 4
        and plan[2] == (0, 5)
        and matrices[0].dtype in (torch.float16, torch.bfloat16)
    ):
        a, b, c, d = matrices
        # These bounds are not independent of ``_mm_last2_kernel``'s hardcoded
        # BLOCK constants (BLOCK_MF=128, BLOCK_NE=64, BLOCK_MO=64): the fused
        # kernel keeps the whole F = B @ E product and the A panel in
        # registers, so it is only correct for shapes that those block sizes
        # tile exactly. b.shape[0] <= 128 <-> BLOCK_MF, d.shape[1] <= 64 <->
        # BLOCK_NE, a.shape[0] <= 64 <-> BLOCK_MO. Changing the block sizes
        # means re-tuning these guards together (and re-running the sweep);
        # changing these guards without the kernel would be a silent
        # correctness bug.
        if (
            b.shape[0] <= 128
            and d.shape[1] <= 64
            and a.shape[0] <= 64
            and a.shape[1] == b.shape[0]
        ):
            e = _mm(c, d)
            return _mm_last2(a, b, e)
    vals = list(matrices)
    for lhs, rhs in plan:
        vals.append(_mm(vals[lhs], vals[rhs]))
    return vals[-1]


def chain_matmul(matrices) -> torch.Tensor:
    """chain_matmul(matrices) -> Tensor : product of the matrix chain (multi_dot).

    Accepts a list/tuple of two or more 2-D tensors. The single-tensor case is
    accepted as well (native returns a clone of it).
    """
    logger.debug("GEMS CHAIN_MATMUL")
    matrices = list(matrices)
    # _check_matrices already rejects the empty list ("Expected one or more
    # matrices") after its per-element dim loop, so no second check is needed
    # here.
    _check_matrices(matrices)
    return _chain_matmul_impl(matrices)


def chain_matmul_out(matrices, *, out=None) -> torch.Tensor:
    """chain_matmul.out(matrices, *, out) -> Tensor : result written into out."""
    logger.debug("GEMS CHAIN_MATMUL OUT")
    if out is None:
        raise RuntimeError("chain_matmul.out: argument 'out' is required")
    matrices = list(matrices)
    _check_matrices(matrices)
    expected_shape = list(matrices[0].shape) if len(matrices) == 1 else None
    if len(matrices) == 1:
        if tuple(out.shape) != tuple(expected_shape):
            out.resize_(expected_shape)
        out.copy_(matrices[0])
        return out
    # Native checks the out dtype/device before doing any computation.
    if out.dtype != matrices[0].dtype:
        raise RuntimeError(
            "multi_dot(): expected out tensor to have dtype "
            f"{matrices[0].dtype} but got {out.dtype}"
        )
    if out.device != matrices[0].device:
        raise RuntimeError(
            "multi_dot(): expected out tensor to be on device "
            f"{matrices[0].device} but got {out.device}"
        )
    result = _chain_matmul_impl(matrices)
    if tuple(out.shape) != tuple(result.shape):
        out.resize_(result.shape)
    out.copy_(result)
    return out
