# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import contextlib
import logging

import torch
import triton
import triton.language as tl
from triton.language.extra import libdevice

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


_MAX_S = 6

# ``_small_path`` packs the whole index array into a single program's lanes
# (BLOCK = 1024); inputs with more stored entries would be silently truncated,
# so ``coalesce`` routes them to ``_scan_path`` instead. Must stay in sync with
# the BLOCK constant inside ``_small_path``.
_SMALL_PATH_MAX = 1024


@triton.jit
def _hist_kernel(
    idx_ptr,
    bits_ptr,
    cnt_ptr,
    n,
    s1,
    s2,
    s3,
    s4,
    s5,
    S: tl.constexpr,
    BLOCK: tl.constexpr,
):
    pid = tl.program_id(0)
    if pid == 0:
        tl.store(cnt_ptr, 0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n
    k = tl.load(idx_ptr + offs, mask=mask, other=0).to(tl.int32)
    if S >= 2:
        i1 = tl.load(idx_ptr + n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s1 + i1
    if S >= 3:
        i2 = tl.load(idx_ptr + 2 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s2 + i2
    if S >= 4:
        i3 = tl.load(idx_ptr + 3 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s3 + i3
    if S >= 5:
        i4 = tl.load(idx_ptr + 4 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s4 + i4
    if S >= 6:
        i5 = tl.load(idx_ptr + 5 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s5 + i5
    w = k >> 5
    bit = 1 << (k & 31)
    tl.atomic_or(bits_ptr + w, bit, mask=mask)


@triton.jit
def _word_scan_kernel(bits_ptr, pack_ptr, blk_tot_ptr, cnt_ptr, n, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n
    v = tl.load(bits_ptr + offs, mask=mask, other=0).to(tl.int32)
    pc = libdevice.popc(v).to(tl.int32)
    s = tl.cumsum(pc, axis=0)
    excl = s - pc
    packed = (excl.to(tl.int64) << 32) | (v.to(tl.int64) & 0xFFFFFFFF)
    tl.store(pack_ptr + offs, packed, mask=mask)
    total = tl.sum(pc, axis=0)
    tl.store(blk_tot_ptr + pid, total)
    if total > 0:
        tl.atomic_add(cnt_ptr, total)


@triton.jit
def _scatter_kernel(
    idx_ptr,
    val_ptr,
    pack_ptr,
    blk_tot_ptr,
    blk_off_ptr,
    acc_ptr,
    out_idx_ptr,
    n,
    nb2,
    s1,
    s2,
    s3,
    s4,
    s5,
    BT: tl.constexpr,
    P1: tl.constexpr,
    P2: tl.constexpr,
    ACC: tl.constexpr,
    S: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # word-block offset scan (nb2 <= ~64) computed in-register per program
    bt_offs = tl.arange(0, BT)
    bt_mask = bt_offs < nb2
    bt = tl.load(blk_tot_ptr + bt_offs, mask=bt_mask, other=0).to(tl.int32)
    bt_s = tl.cumsum(bt, axis=0)
    bt_excl = bt_s - bt
    tl.store(blk_off_ptr + bt_offs, bt_excl, mask=bt_mask)
    tl.debug_barrier()

    offs = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offs < n
    k = tl.load(idx_ptr + offs, mask=mask, other=0).to(tl.int32)
    if S >= 2:
        i1 = tl.load(idx_ptr + n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s1 + i1
    if S >= 3:
        i2 = tl.load(idx_ptr + 2 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s2 + i2
    if S >= 4:
        i3 = tl.load(idx_ptr + 3 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s3 + i3
    if S >= 5:
        i4 = tl.load(idx_ptr + 4 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s4 + i4
    if S >= 6:
        i5 = tl.load(idx_ptr + 5 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s5 + i5
    w = k >> 5
    b = k & 31
    pv = tl.load(pack_ptr + w, mask=mask, other=0)
    wv = (pv & 0xFFFFFFFF).to(tl.int32)
    base = (pv >> 32).to(tl.int32)
    pc = libdevice.popc(wv & ((1 << b) - 1)).to(tl.int32)
    blk2 = w >> 13
    pos = base + pc + tl.load(blk_off_ptr + blk2, mask=mask, other=0)
    v = tl.load(val_ptr + offs, mask=mask, other=0)
    # ACC mirrors the small-path accumulation convention (see ``_small_path``):
    # 0 = fp64, 1 = int64, 2 = int32, 3 = fp32. The accumulator buffer is
    # allocated with the matching dtype, so each non-float dtype accumulates
    # exactly like the small path would (no intermediate fp32 rounding).
    if ACC == 0:
        va = v.to(tl.float64)
    elif ACC == 1:
        va = v.to(tl.int64)
    elif ACC == 2:
        va = v.to(tl.int32)
    else:
        va = v.to(tl.float32)
    tl.atomic_add(acc_ptr + pos, va, mask=mask)
    kk = k
    if S >= 6:
        i5o = kk % s5
        kk = kk // s5
        tl.store(out_idx_ptr + 5 * n + pos, i5o.to(tl.int64), mask=mask)
    if S >= 5:
        i4o = kk % s4
        kk = kk // s4
        tl.store(out_idx_ptr + 4 * n + pos, i4o.to(tl.int64), mask=mask)
    if S >= 4:
        i3o = kk % s3
        kk = kk // s3
        tl.store(out_idx_ptr + 3 * n + pos, i3o.to(tl.int64), mask=mask)
    if S >= 3:
        if P2 >= 0:
            i2o = kk & ((1 << P2) - 1)
            kk = kk >> P2
        else:
            i2o = kk % s2
            kk = kk // s2
        tl.store(out_idx_ptr + 2 * n + pos, i2o.to(tl.int64), mask=mask)
    if S >= 2:
        if P1 >= 0:
            i1o = kk & ((1 << P1) - 1)
            kk = kk >> P1
        else:
            i1o = kk % s1
            kk = kk // s1
        tl.store(out_idx_ptr + n + pos, i1o.to(tl.int64), mask=mask)
    tl.store(out_idx_ptr + pos, kk.to(tl.int64), mask=mask)


@triton.jit
def _finalize_kernel(acc_ptr, out_ptr, r, IS_BOOL: tl.constexpr, BLOCK: tl.constexpr):
    offs = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offs < r
    v = tl.load(acc_ptr + offs, mask=mask, other=0)
    if IS_BOOL:
        tl.store(out_ptr + offs, v != 0, mask=mask)
    else:
        tl.store(out_ptr + offs, v.to(out_ptr.dtype.element_ty), mask=mask)


@triton.jit
def _small_sort_kernel(
    idx_ptr,
    spack_ptr,
    n,
    shift,
    s1,
    s2,
    s3,
    s4,
    s5,
    S: tl.constexpr,
    BLOCK: tl.constexpr,
):
    offs = tl.arange(0, BLOCK)
    mask = offs < n
    k = tl.load(idx_ptr + offs, mask=mask, other=0).to(tl.int32)
    if S >= 2:
        i1 = tl.load(idx_ptr + n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s1 + i1
    if S >= 3:
        i2 = tl.load(idx_ptr + 2 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s2 + i2
    if S >= 4:
        i3 = tl.load(idx_ptr + 3 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s3 + i3
    if S >= 5:
        i4 = tl.load(idx_ptr + 4 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s4 + i4
    if S >= 6:
        i5 = tl.load(idx_ptr + 5 * n + offs, mask=mask, other=0).to(tl.int32)
        k = k * s5 + i5
    packed = (k.to(tl.int64) << shift.to(tl.int64)) | offs.to(tl.int64)
    packed = tl.where(mask, packed, (1 << 63) - 1)
    sp = tl.sort(packed, dim=0)
    tl.store(spack_ptr + offs, sp)


@triton.jit
def _small_run_kernel(
    spack_ptr,
    val_ptr,
    acc_ptr,
    out_idx_ptr,
    cnt_ptr,
    n,
    shift,
    p_mask,
    s1,
    s2,
    s3,
    s4,
    s5,
    ACC: tl.constexpr,
    S: tl.constexpr,
    BLOCK: tl.constexpr,
):
    offs = tl.arange(0, BLOCK)
    mask = offs < n
    sp = tl.load(spack_ptr + offs, mask=mask, other=0)
    key_s = (sp >> shift.to(tl.int64)).to(tl.int32)
    p = (sp & p_mask.to(tl.int64)).to(tl.int32)
    sp_prev = tl.load(spack_ptr + offs - 1, mask=(offs > 0) & mask, other=-1)
    key_prev = (sp_prev >> shift.to(tl.int64)).to(tl.int32)
    is_first = (offs == 0) | (key_s != key_prev)
    fi = is_first.to(tl.int32)
    pos = tl.cumsum(fi, axis=0) - 1
    total = tl.sum(tl.where(mask, fi, 0), axis=0)
    if total > 0:
        tl.atomic_add(cnt_ptr, total)
    v = tl.load(val_ptr + p, mask=mask, other=0)
    if ACC == 0:
        va = v.to(tl.float64)
    elif ACC == 1:
        va = v.to(tl.int64)
    else:
        va = v.to(tl.int32)
    tl.atomic_add(acc_ptr + pos, va, mask=mask)
    kk = key_s
    if S >= 6:
        i5o = kk % s5
        kk = kk // s5
        tl.store(out_idx_ptr + 5 * n + pos, i5o.to(tl.int64), mask=mask)
    if S >= 5:
        i4o = kk % s4
        kk = kk // s4
        tl.store(out_idx_ptr + 4 * n + pos, i4o.to(tl.int64), mask=mask)
    if S >= 4:
        i3o = kk % s3
        kk = kk // s3
        tl.store(out_idx_ptr + 3 * n + pos, i3o.to(tl.int64), mask=mask)
    if S >= 3:
        i2o = kk % s2
        kk = kk // s2
        tl.store(out_idx_ptr + 2 * n + pos, i2o.to(tl.int64), mask=mask)
    if S >= 2:
        i1o = kk % s1
        kk = kk // s1
        tl.store(out_idx_ptr + n + pos, i1o.to(tl.int64), mask=mask)
    tl.store(out_idx_ptr + pos, kk.to(tl.int64), mask=mask)


@triton.jit
def _small_finalize_kernel(
    acc_ptr, out_ptr, r, IS_BOOL: tl.constexpr, BLOCK: tl.constexpr
):
    offs = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offs < r
    v = tl.load(acc_ptr + offs, mask=mask, other=0)
    if IS_BOOL:
        tl.store(out_ptr + offs, v != 0, mask=mask)
    else:
        tl.store(out_ptr + offs, v.to(out_ptr.dtype.element_ty), mask=mask)


def _shapes(S, shape):
    s = [1] * (_MAX_S - 1)
    for d in range(1, _MAX_S):
        if d < S:
            s[d - 1] = shape[d]
    return s


def _log2(x):
    if x > 0 and (x & (x - 1)) == 0:
        return x.bit_length() - 1
    return -1


def _scan_path(idx, val, shape, S, n, dt, dev):
    """Multi-program histogram + scan + scatter path (any nnz).

    Historically this served only fp16/fp32/bf16, accumulating in fp32; it now
    also serves the small path's dtypes whenever ``nnz > _SMALL_PATH_MAX`` so
    that no dtype is truncated. The accumulation dtype follows the small
    path's convention via ``ACC`` (0 = fp64, 1 = int64, 2 = int32, 3 = fp32),
    so results match what ``_small_path`` would produce, bit for bit, just
    without its 1024-entry ceiling.
    """
    K = 1
    for x in shape:
        K *= x
    s1, s2, s3, s4, s5 = _shapes(S, shape)
    p1 = _log2(shape[1]) if S >= 2 else -1
    p2 = _log2(shape[2]) if S >= 3 else -1

    B = 1024
    NW = (K + 31) // 32

    # One allocation per purpose: ``bits`` is the per-index bit histogram and
    # ``acc`` the per-unique-entry accumulator. They used to share a single
    # int32 buffer (``buf = zeros(NW + n); val32 = buf[NW:].view(float32)``),
    # which relied on the zeroed tail and made the lifetimes hard to follow.
    bits = torch.zeros(NW, dtype=torch.int32, device=dev)
    pack = torch.empty(NW, dtype=torch.int64, device=dev)
    nb2 = (NW + 8191) // 8192
    blk_tot = torch.empty(nb2, dtype=torch.int32, device=dev)
    blk_off = torch.empty(nb2, dtype=torch.int32, device=dev)
    cnt = torch.empty(1, dtype=torch.int32, device=dev)
    if dt == torch.float32:
        acc = torch.zeros(n, dtype=torch.float32, device=dev)
        acc_code = 3
    elif dt == torch.float64:
        acc = torch.zeros(n, dtype=torch.float64, device=dev)
        acc_code = 0
    elif dt == torch.int64:
        acc = torch.zeros(n, dtype=torch.int64, device=dev)
        acc_code = 1
    else:
        # fp16/bf16 keep fp32 accumulation (matching the historical float
        # path); narrower ints and bool accumulate in int32 exactly like the
        # small path. Only fp32 skips the finalize cast (see below); fp16/bf16
        # are finalized down to their own dtype.
        acc = torch.zeros(
            n, dtype=torch.float32 if dt.is_floating_point else torch.int32, device=dev
        )
        acc_code = 3 if dt.is_floating_point else 2
    out_idx = torch.empty(S * n, dtype=torch.int64, device=dev)

    _hist_kernel[(triton.cdiv(n, B),)](
        idx, bits, cnt, n, s1, s2, s3, s4, s5, S=S, BLOCK=B
    )
    _word_scan_kernel[(nb2,)](bits, pack, blk_tot, cnt, NW, BLOCK=8192, num_warps=8)
    _scatter_kernel[(triton.cdiv(n, B),)](
        idx,
        val,
        pack,
        blk_tot,
        blk_off,
        acc,
        out_idx,
        n,
        nb2,
        s1,
        s2,
        s3,
        s4,
        s5,
        BT=triton.next_power_of_2(nb2),
        P1=p1,
        P2=p2,
        ACC=acc_code,
        S=S,
        BLOCK=B,
        num_warps=8,
    )
    r = int(cnt)
    if dt == torch.float32:
        # acc already holds fp32: serve the values directly.
        ov = acc[:r]
    else:
        out_val = torch.empty(n, dtype=dt, device=dev)
        _finalize_kernel[(triton.cdiv(r, B),)](
            acc, out_val, r, IS_BOOL=(dt == torch.bool), BLOCK=B
        )
        ov = out_val[:r]
    oi = out_idx.view(S, n)[:, :r]
    return torch.sparse_coo_tensor(oi, ov, shape)


def _small_path(idx, val, shape, S, n, dt, dev):
    """Single-program sort + accumulate path, correct for ``n <= _SMALL_PATH_MAX``.

    The whole index array is packed into one int64 key per entry
    (``key << shift | position``) and sorted with ``tl.sort`` inside a single
    program, so the working set is bounded by BLOCK = 1024 lanes. Inputs above
    that bound are routed to ``_scan_path`` by ``coalesce``; this function must
    never see ``n > _SMALL_PATH_MAX``.
    """
    s1, s2, s3, s4, s5 = _shapes(S, shape)
    if dt == torch.float64:
        acc_dt = torch.float64
        acc_code = 0
    elif dt == torch.int64:
        acc_dt = torch.int64
        acc_code = 1
    else:
        acc_dt = torch.int32
        acc_code = 2

    BLOCK = 1024
    shift = (n - 1).bit_length() if n > 1 else 0
    p_mask = (1 << shift) - 1 if shift > 0 else 0

    spack = torch.empty(BLOCK, dtype=torch.int64, device=dev)
    acc = torch.zeros(BLOCK, dtype=acc_dt, device=dev)
    cnt = torch.zeros(1, dtype=torch.int32, device=dev)
    out_idx = torch.empty(S * n, dtype=torch.int64, device=dev)
    out_val = torch.empty(n, dtype=dt, device=dev)

    _small_sort_kernel[(1,)](idx, spack, n, shift, s1, s2, s3, s4, s5, S=S, BLOCK=BLOCK)
    _small_run_kernel[(1,)](
        spack,
        val,
        acc,
        out_idx,
        cnt,
        n,
        shift,
        p_mask,
        s1,
        s2,
        s3,
        s4,
        s5,
        ACC=acc_code,
        S=S,
        BLOCK=BLOCK,
    )
    r = int(cnt)
    _small_finalize_kernel[(triton.cdiv(r, BLOCK),)](
        acc, out_val, r, IS_BOOL=(dt == torch.bool), BLOCK=BLOCK
    )
    oi = out_idx.view(S, n)[:, :r]
    ov = out_val[:r]
    return torch.sparse_coo_tensor(oi, ov, shape)


def coalesce(self: torch.Tensor) -> torch.Tensor:
    """Sort a sparse COO tensor's indices and merge duplicate entries.

    Mirrors ``aten::coalesce(Tensor(a) self) -> Tensor(a)``. The returned
    tensor is a fresh sparse COO tensor whose indices are sorted in
    lexicographic (row-major) order and whose duplicate entries have had
    their values added together; the returned tensor reports
    ``is_coalesced() == True``. The input tensor is never modified: when it
    is already coalesced (or has zero stored entries, which native treats as
    coalesced) the *same object* is returned, exactly as native does.

    Two kernel paths mirror the source: a scan path (fp16/fp32/bf16, and any
    dtype whose stored-entry count exceeds the small path's 1024-entry
    ceiling) built on a 32-bit per-element bit histogram + word scan + atomic
    scatter that accumulates in fp32 for floats and fp64/int64/int32 for the
    small path's dtypes, and a small path (fp64/ints/bool with at most 1024
    stored entries) that sorts the whole index array in one program and
    accumulates in fp64/int64/int32.

    The op is registered with the CompositeImplicitAutograd dispatch key,
    which is the only key that reaches it on this build (measured, see
    runs/coalesce/probe*.log): native ``aten::coalesce`` has no backend key
    at all, and the composite kernel is a decomposition, not an
    implementation. Delegating to the native composite from inside this
    function is impossible because that composite *is* this registration;
    calling ``_coalesced_(True)`` on the result restores the flag with the
    native metadata mutation.
    """
    logger.debug("GEMS COALESCE")
    if self.layout != torch.sparse_coo:
        # Native wording (SparseTensor.cpp): "coalesce expected sparse
        # coordinate tensor layout but got <layout>" where <layout> is the
        # layout's C++ enum name (Strided / SparseCsr / SparseBsc ...). This
        # must run BEFORE any metadata access: a strided tensor rejects with
        # this error rather than a NotImplementedError from ``_nnz``.
        raw = str(self.layout).replace("torch.", "")
        parts = raw.split("_")
        layout = "".join(p[:1].upper() + p[1:] for p in parts)
        raise RuntimeError(
            f"coalesce expected sparse coordinate tensor layout but got {layout}"
        )
    shape = tuple(self.shape)
    n = self._nnz()
    S = self.sparse_dim()
    D = self.dense_dim()
    dt = self.dtype
    if self.is_coalesced() or n == 0:
        return self
    idx = self._indices()
    val = self._values()
    dev = self.device
    if D > 0:
        # Hybrid COO (values with trailing dense dims) is unsupported by the
        # supplied kernels: they address ``val_ptr + offs`` with a scalar
        # offset, which reads only the first dense column, and the output is
        # built with a 1-D value tensor, which ``torch.sparse_coo_tensor``
        # rejects for a shape with dense dims. Native instead adds whole
        # value rows (values.stride(0) blocks). Because the op carries no
        # backend key, this override cannot fall back to the native composite
        # either; the limitation is disclosed in the report.
        raise NotImplementedError(
            "coalesce does not support hybrid COO tensors with dense dimensions "
            f"(sparse_dim={S}, dense_dim={D}); the submitted kernel accumulation "
            "is defined for 1-D values only"
        )
    # ``torch_device_fn.device`` is accelerator-specific and raises ValueError
    # for a CPU device; the Triton kernels below are a GPU implementation, so a
    # CPU tensor cannot be served here either. The context is entered for every
    # accelerator device and skipped only for CPU (the CI --ref=cpu phase keeps
    # the implementation input on the accelerator; this is purely defensive).
    if dev.type == "cpu":
        ctx = contextlib.nullcontext()
    else:
        ctx = torch_device_fn.device(dev)
    with ctx:
        if dt in (torch.float16, torch.float32, torch.bfloat16):
            out = _scan_path(idx, val, shape, S, n, dt, dev)
        elif n <= _SMALL_PATH_MAX:
            out = _small_path(idx, val, shape, S, n, dt, dev)
        else:
            # The small path is single-program (BLOCK = 1024 lanes) and would
            # silently drop everything past lane 1023; larger non-float inputs
            # take the multi-program scan path with the same accumulation
            # dtype the small path would have used.
            out = _scan_path(idx, val, shape, S, n, dt, dev)
    out._coalesced_(True)
    return out
