# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _copy_fused(si, di, ni, sv, dv, nv, split, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    if pid < split:
        offs = pid * BLOCK + tl.arange(0, BLOCK)
        mask = offs < ni
        tl.store(di + offs, tl.load(si + offs, mask=mask), mask=mask)
    else:
        pid2 = pid - split
        offs = pid2 * BLOCK + tl.arange(0, BLOCK)
        mask = offs < nv
        tl.store(dv + offs, tl.load(sv + offs, mask=mask), mask=mask)


# Unmasked variant: reachable only on the big-block path (BLOCK == _BLOCK_BIG
# = 2048, i.e. only when ni + nv >= _BIG_THRESH) AND both streams exactly
# BLOCK-divisible — the guard below also demands ni % BLOCK == 0 and
# nv % BLOCK == 0, so on the small-block path (_BLOCK_SMALL = 1024) this
# kernel never runs even when the streams are divisible. True for every
# benchmark workload. Consistently ~0.5-0.7us faster on the fp32
# indices-heavy large workloads in interleaved A/B screening.
@triton.jit
def _copy_fused_nomask(si, di, ni, sv, dv, nv, split, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    if pid < split:
        offs = pid * BLOCK + tl.arange(0, BLOCK)
        tl.store(di + offs, tl.load(si + offs))
    else:
        pid2 = pid - split
        offs = pid2 * BLOCK + tl.arange(0, BLOCK)
        tl.store(dv + offs, tl.load(sv + offs))


# Small workloads are launch-bound (BLOCK=1024); large workloads get a
# slightly higher-bandwidth values stream with BLOCK=2048.
_BLOCK_SMALL = 1024
_BLOCK_BIG = 2048
_NW = 4
_BIG_THRESH = 2_500_000


def _fused_copy(src_idx, dst_idx, src_val, dst_val, device):
    """Copy the indices stream (``src_idx -> dst_idx``) and the values stream
    (``src_val -> dst_val``) with one fused kernel launch.

    Kept from the supplied source verbatim: the BLOCK/num_warps choices, the
    size threshold, the masked/nomask kernel selection and the split arithmetic
    are unchanged. The source guarded all of that behind ``if ni + nv > 0:``;
    the same skip is expressed here as an explicit early return for the
    both-streams-empty case.
    """
    ni = src_idx.numel()
    nv = src_val.numel()
    if ni + nv == 0:
        # Both streams empty: there is nothing to copy and no grid to launch;
        # an explicit return keeps the BLOCK/threshold selection below tied to
        # at least one non-empty stream.
        return
    BLOCK = _BLOCK_BIG if ni + nv >= _BIG_THRESH else _BLOCK_SMALL
    split = (ni + BLOCK - 1) // BLOCK
    grid = (split + (nv + BLOCK - 1) // BLOCK,)
    if BLOCK == _BLOCK_BIG and ni % BLOCK == 0 and nv % BLOCK == 0:
        _copy_fused_nomask[grid](
            src_idx,
            dst_idx,
            ni,
            src_val,
            dst_val,
            nv,
            split,
            BLOCK=BLOCK,
            num_warps=_NW,
        )
    else:
        _copy_fused[grid](
            src_idx,
            dst_idx,
            ni,
            src_val,
            dst_val,
            nv,
            split,
            BLOCK=BLOCK,
            num_warps=_NW,
        )


def _grow_error(kind, before, after):
    return (
        f"{kind} (from {before} to {after}) on a non-empty sparse tensor is not supported.\n"
        "You could try the following options:\n"
        "1. If you need an empty sparse tensor of this size, call "
        "`x = torch.sparse_coo_tensor(size)`.\n"
        "2. If you need to resize this tensor, you have the following options:\n"
        "    1. For both sparse and dense dimensions, keep the number of them "
        "constant and the size of them non-shrinking, and then try the same "
        "call again.\n"
        "    2. Or, create a new sparse tensor with the correct indices and "
        "values from this sparse tensor."
    )


def _contiguous_buffers(t, name):
    """Return ``(indices, values)`` of ``t`` guaranteed contiguous in storage.

    The fused kernels below address the copies with a single base pointer plus
    a linear ``tl.arange`` offset, so they walk the buffer as if it were flat:
    ``di + offs`` for ``offs < numel``. That is only correct when the buffer's
    layout equals its logical layout. torch happily accepts and preserves a COO
    tensor whose buffers are not contiguous, including stride 0
    (``torch.sparse_coo_tensor(idx, values.expand(...), shape)`` stores the
    ``expand`` view itself — measured), so a linear walk over such a buffer
    reads or writes past the end of the storage when the strides are 0, and
    silently permutes the elements when they are not. Native never sees this
    problem because it copies through a strided tensor iterator.

    Materialising a contiguous copy here is the cheapest correct answer: these
    tensors are 1-D/n-D buffers of exactly ``numel`` elements, the copy is
    O(nnz * dense) and the copy itself is already O(nnz * dense). It is also
    what the caller's own allocation does right below (``torch.empty_like`` on
    a non-expanded source preserves memory format), so the kernel no longer
    depends on a property of the input that nothing in this repository
    enforces. ``contiguous()`` is a no-op returning ``self`` when the buffer is
    already contiguous — the case of every ordinary COO tensor — so no
    workload pays for the check.
    """
    idx, val = t._indices(), t._values()
    if not idx.is_contiguous():
        logger.debug(
            "GEMS COPY_SPARSE_TO_SPARSE_ %s: materialising indices "
            "(shape=%s, nnz=%d)",
            name,
            tuple(t.shape),
            t._nnz(),
        )
        idx = idx.contiguous()
    if not val.is_contiguous():
        logger.debug(
            "GEMS COPY_SPARSE_TO_SPARSE_ %s: materialising values "
            "(shape=%s, nnz=%d)",
            name,
            tuple(t.shape),
            t._nnz(),
        )
        val = val.contiguous()
    return idx, val


def copy_sparse_to_sparse_(
    self: torch.Tensor, src: torch.Tensor, non_blocking: bool = False
) -> torch.Tensor:
    """Copy one sparse COO tensor into another, in place.

    Mirrors ``aten::copy_sparse_to_sparse_(Tensor(a!) self, Tensor src, bool
    non_blocking=False) -> Tensor(a!)``: ``self`` receives ``src``'s stored
    entries and is returned. Measured native ATen behaviour (H20, container
    torch 2.8.0a0, and identical on CPU):

    - ``self is src``: no-op, ``self`` is returned untouched;
    - identical structure (same shape, nnz and sparse/dense split): the
      stored entries are copied into ``self``'s existing buffers and the
      coalesced flag becomes ``src``'s;
    - different structure: native runs ``SparseTensorImpl::resize_`` (which
      allows only non-shrinking changes of the sizes, and only on an empty
      tensor a change of the sparse/dense split) and then copies into **fresh**
      buffers, casting the values to ``self``'s dtype;
    - shrink of any dimension, or a sparse/dense split change, on a non-empty
      ``self`` raises ``RuntimeError``, leaving ``self`` untouched.

    Two behaviours of the supplied source were corrected against measured
    native ATen, both disclosed here (they are rejection/validation logic, not
    computation):

    - the source never validates the resize: it silently rewrote ``self`` for
      a shrinking or split-changing ``src`` where native raises the grow-only
      ``RuntimeError`` of ``SparseTensorImpl::_resize_``. The rejections are
      reproduced here, before any mutation;
    - the source rebuilt ``self`` from a fresh ``torch.sparse_coo_tensor``:
      that constructor recomputes the coalesced flag from ``nnz < 2`` and keeps
      the source values' dtype, while native hands over fresh buffers in
      ``self``'s dtype and ends with ``self._coalesced_(src.is_coalesced())``.
      The structural path now allocates in ``self``'s dtype, casts the copied
      values, and restores the flag from ``src``.

    The supplied package hands the new tensor over with
    ``torch.utils.swap_tensors(self, new_sp)``. That call does not survive
    dispatch: reached through ``torch.ops.aten`` the tensor carries one extra
    internal reference (``self._use_count() == 3`` instead of 1) and
    ``swap_tensors`` refuses to run with ``use_count > 1`` (measured on H20,
    job ``copy_sparse_to_sparse_-other-a1-2e0cef4c``). The ``Tensor.data``
    setter rebinds the same ``TensorImpl`` with no such precondition, and was
    measured (job ``copy_sparse_to_sparse_-other-a1-cf708fed``) to give the
    identical observable end state: the result ``is`` the argument and every
    other Python name for the object sees the new metadata.

    Non-COO inputs: the native kernel table has no kernel for compressed
    layouts (CSR/CSC/BSR/BSC raise the dispatcher's ``NotImplementedError``)
    and no plain-CUDA kernel either, so strided tensors cannot reach a native
    kernel. Registering this implementation on the backend keys (which the
    repository registrar always does) would otherwise make those inputs
    silently proceed, so non-COO layouts are rejected here explicitly with
    the class native raises for each family (measured on CPU and H20:
    compressed -> NotImplementedError, strided -> RuntimeError).

    The fused Triton kernels, the BLOCK/num_warps choices, the size threshold
    and the masked/nomask selection are kept from the supplied source exactly;
    the small-block/no-op/self-copy short-circuits are unchanged.

    ``non_blocking`` is accepted only to match the aten signature and is
    deliberately never read. Native forwards it to
    ``copy_into_sparse``, which passes it on to
    ``indices.to(options, non_blocking, copy=true)`` — the single place the
    flag reaches, and one where it is observable only on the
    host<->device branch of ``Tensor.to()``. This implementation is a
    device-to-device fused copy that never moves a tensor across the
    host/device boundary, so there is no native effect left to reproduce and
    ignoring the flag is equivalent (the default path of that ``to()`` is
    asynchronous for device-to-device moves either way). The parameter keeps
    its name and position for the aten signature match.
    """
    logger.debug("GEMS COPY_SPARSE_TO_SPARSE_")
    if self.layout != torch.sparse_coo or src.layout != torch.sparse_coo:
        # Native has no kernel for a compressed layout on either side (the
        # dispatcher raises NotImplementedError for SparseCsr*/Sparse*B inputs)
        # and no kernel for strided tensors either, where a COO operand makes
        # the call fail inside the native resize with RuntimeError. The
        # class split is measured (CPU and H20 agree): any compressed layout
        # on either side -> NotImplementedError, any strided operand ->
        # RuntimeError. Registering this implementation on the backend keys
        # (which the repository registrar always does) would otherwise make
        # those inputs silently proceed, so they are rejected here.
        compressed = (
            torch.sparse_csr,
            torch.sparse_csc,
            torch.sparse_bsr,
            torch.sparse_bsc,
        )
        if self.layout in compressed or src.layout in compressed:
            raise NotImplementedError(
                "copy_sparse_to_sparse_ is not implemented for compressed "
                "sparse layouts; got self layout "
                + str(self.layout)
                + " and src layout "
                + str(src.layout)
            )
        raise RuntimeError(
            "copy_sparse_to_sparse_ expected a sparse coordinate (coo) tensor "
            "on both sides; got self layout "
            + str(self.layout)
            + " and src layout "
            + str(src.layout)
        )

    if self is src:
        return self

    s_idx, s_val = _contiguous_buffers(src, "src")

    structural = (
        self._nnz() != src._nnz()
        or self.shape != src.shape
        or self.sparse_dim() != src.sparse_dim()
        or self.dense_dim() != src.dense_dim()
        # A destination whose buffers are not contiguous in storage cannot be
        # the target of the linear kernel walk either, and unlike the source it
        # cannot be fixed by a local ``contiguous()``: the buffers are the ones
        # the caller (and every alias of ``self``) addresses afterwards, so a
        # local copy would be dead work. Measured on CPU with a stride-0 dst:
        # native does not write into the strided buffer either — after the call
        # ``self._values()`` is contiguous and backed by a full-size storage —
        # which is what the structural path below produces (fresh contiguous
        # buffers holding the copied entries). With shape / nnz / split equal
        # its resize is a no-op, so routing here reproduces native's end state.
        or not self._indices().is_contiguous()
        or not self._values().is_contiguous()
    )

    if structural:
        # One-time structural resize. Native mirrors
        # SparseTensorImpl::_resize_ + copy_into_sparse: the resize accepts
        # only non-shrinking size changes (and a split change only on an
        # empty tensor), and the copy lands in fresh buffers cast to self's
        # dtypes. Every validation happens before any mutation.
        if self._nnz() > 0:
            if self.sparse_dim() != src.sparse_dim():
                raise RuntimeError(
                    _grow_error(
                        "changing the number of sparse dimensions",
                        self.sparse_dim(),
                        src.sparse_dim(),
                    )
                )
            if self.dense_dim() != src.dense_dim():
                raise RuntimeError(
                    _grow_error(
                        "changing the number of dense dimensions",
                        self.dense_dim(),
                        src.dense_dim(),
                    )
                )
            for i in range(self.sparse_dim()):
                if src.shape[i] < self.shape[i]:
                    raise RuntimeError(
                        _grow_error(
                            "shrinking the size of sparse dimensions",
                            list(self.shape[: self.sparse_dim()]),
                            list(src.shape[: self.sparse_dim()]),
                        )
                    )
            for i in range(self.dense_dim()):
                if src.shape[self.sparse_dim() + i] < self.shape[self.sparse_dim() + i]:
                    raise RuntimeError(
                        _grow_error(
                            "shrinking the size of dense dimensions",
                            list(self.shape[self.sparse_dim() :]),
                            list(src.shape[self.sparse_dim() :]),
                        )
                    )

        new_i = torch.empty_like(s_idx, dtype=self._indices().dtype, device=self.device)
        new_v = torch.empty_like(s_val, dtype=self._values().dtype, device=self.device)
        with torch_device_fn.device(self.device):
            # The kernel stores element-typed values into the destination
            # buffers, so a values cast between src and self dtypes is
            # performed on the host side first (native copy_into_sparse
            # semantics: values land in self's dtype).
            if new_v.dtype != s_val.dtype:
                s_val = s_val.to(new_v.dtype)
            _fused_copy(s_idx, new_i, s_val, new_v, self.device)
        new_sp = torch.sparse_coo_tensor(
            new_i, new_v, tuple(src.shape), device=self.device
        )
        new_sp._coalesced_(src.is_coalesced())
        self.data = new_sp
        return self

    d_idx = self._indices()
    d_val = self._values()
    with torch_device_fn.device(self.device):
        _fused_copy(s_idx, d_idx, s_val, d_val, self.device)
    # Native ends every copy with self._coalesced_(src.is_coalesced()); the
    # same-structure path must do the same (the buffers are already self's).
    # The flip is dispatched below the in-place view layer: that layer is what
    # bumps the version counter on the dispatched path, and it has already
    # bumped it once for this call, so an unguarded second in-place op would
    # count twice where native counts once (measured on H20).
    if self.is_coalesced() != src.is_coalesced():
        with torch._C._AutoDispatchBelowADInplaceOrView():
            torch.ops.aten._coalesced_(self, src.is_coalesced())
    return self
